Repository inspec/inspec-aws, pull requests merged in 2021-05, with the labels that each got.

#335 Adding aws cloudformation stacks resource
  README.md
  docs/resources/aws_cloudformation_stacks.md
  libraries/aws_cloudformation_stacks.rb
  test/integration/verify/controls/aws_cloudformation_stacks.rb
  test/unit/resources/aws_cloudformation_stacks_test.rb
  test/unit/resources/mock/aws_cloudformation_stack_mock.rb
Labels: Documentation, Version: Bump Minor

#358 aws_auto_scaling_groups lint error fix
  libraries/aws_auto_scaling_group.rb
  libraries/aws_auto_scaling_groups.rb
Labels: Bug

#354 Adding aws ecr policy resource
  README.md
  docs/resources/aws_ecr_repository_policy.md
  libraries/aws_ecr_repository_policy.rb
  test/integration/build/.terraform.lock.hcl
  test/integration/build/aws.tf
  test/integration/verify/controls/aws_ecr_repository_policy.rb
  test/unit/resources/aws_ecr_repository_policy_test.rb
  test/unit/resources/mock/aws_ecr_repository_policy_mock.rb
Labels: Documentation, Version: Bump Minor

#325 Support ec2 dhcp options
  README.md
  docs/resources/aws_dhcp_options.md
  docs/resources/aws_ec2_dhcp_option.md
  docs/resources/aws_ec2_dhcp_options.md
  libraries/aws_dhcp_options.rb
  libraries/aws_ec2_dhcp_option.rb
  libraries/aws_ec2_dhcp_options.rb
  test/integration/verify/controls/aws_ec2_dhcp_option.rb
  test/integration/verify/controls/aws_ec2_dhcp_options.rb
  test/unit/resources/aws_ec2_dhcp_option_test.rb
  test/unit/resources/aws_ec2_dhcp_options_test.rb
  test/unit/resources/mock/aws_ec2_dhcp_option_mock.rb
Labels: Documentation, Version: Bump Minor

#327 Added Support to Audit Launch Template resource
  README.md
  docs/resources/aws_ec2_launch_template.md
  docs/resources/aws_ec2_launch_templates.md
  libraries/aws_ec2_launch_template.rb
  libraries/aws_ec2_launch_templates.rb
  test/integration/build/aws.tf
  test/integration/build/outputs.tf
  test/integration/configuration/aws_inspec_config.rb
  test/integration/verify/controls/aws_ec2_launch_template.rb
  test/integration/verify/controls/aws_ec2_launch_templates.rb
  test/unit/resources/aws_ec2_launch_template_test.rb
  test/unit/resources/aws_ec2_launch_templates_test.rb
Labels: Component: Chef InSpec, Documentation, Version: Bump Minor

#338 Support vpn gateway resource
  README.md
  docs/resources/aws_vpn_gateway.md
  docs/resources/aws_vpn_gateways.md
  libraries/aws_vpn_gateway.rb
  libraries/aws_vpn_gateways.rb
  test/integration/build/aws.tf
  test/integration/build/outputs.tf
  test/integration/configuration/aws_inspec_config.rb
  test/integration/verify/controls/aws_vpn_gateway.rb
  test/integration/verify/controls/aws_vpn_gateways.rb
  test/unit/resources/aws_vpn_gateway_test.rb
  test/unit/resources/aws_vpn_gateways_test.rb
  test/unit/resources/mock/aws_vpn_gateway_mock.rb
Labels: Documentation, Feature Request, Version: Bump Minor

#350 Soumyo/ec2 routes
  docs/resources/aws_route_table.md
  docs/resources/aws_route_tables.md
  libraries/aws_route_tables.rb
  test/integration/build/.terraform.lock.hcl
  test/integration/build/aws.tf
  test/integration/build/files/lambda.zip
  test/integration/build/outputs
  test/integration/verify/controls/aws_route_table.rb
  test/integration/verify/controls/aws_route_tables.rb
  test/unit/resources/aws_route_table_test.rb
  test/unit/resources/aws_route_tables_test.rb
Labels: Documentation

#344 Soumyo/ec2 transit gateway route table
  README.md
  docs/resources/aws_ec2_transit_gateway_route_table.md
  docs/resources/aws_ec2_transit_gateway_route_tables.md
  libraries/aws_ec2_transit_gateway_route_table.rb
  libraries/aws_ec2_transit_gateway_route_tables.rb
  test/integration/build/aws.tf
  test/integration/build/outputs
  test/integration/verify/controls/aws_ec2_transit_gateway_route_table.rb
  test/integration/verify/controls/aws_ec2_transit_gateway_route_tables.rb
  test/unit/resources/aws_ec2_transit_gateway_route_table_test.rb
  test/unit/resources/aws_ec2_transit_gateway_route_tables_test.rb
Labels: Documentation, Feature Request

#343 Soumyo/ec2 transit gateway attachment
  README.md
  docs/resources/aws_ec2_transit_gateway_attachment.md
  docs/resources/aws_ec2_transit_gateway_attachments.md
  libraries/aws_ec2_transit_gateway_attachment.rb
  libraries/aws_ec2_transit_gateway_attachments.rb
  test/integration/build/aws.tf
  test/integration/build/outputs
  test/integration/verify/controls/aws_ec2_transit_gateway_attachment.rb
  test/integration/verify/controls/aws_ec2_transit_gateway_attachments.rb
  test/unit/resources/aws_ec2_transit_gateway_attachment_test.rb
  test/unit/resources/aws_ec2_transit_gateway_attachments_test.rb
Labels: Documentation, Feature Request

#353 added support for aws rds group option
  README.md
  docs/resources/aws_rds_group_option.md
  docs/resources/aws_rds_group_options.md
  libraries/aws_rds_option_group.rb
  libraries/aws_rds_option_groups.rb
  test/integration/build/aws.tf
  test/integration/build/files/lambda.zip
  test/integration/build/outputs.tf
  test/integration/configuration/aws_inspec_config.rb
  test/integration/verify/controls/aws_rds_option_group.rb
  test/integration/verify/controls/aws_rds_option_groups.rb
  test/unit/resources/aws_rds_option_group_test.rb
  test/unit/resources/aws_rds_option_groups_test.rb
Labels: Documentation, Feature Request, Version: Bump Minor

#359 added support for Redshift Clusters
  README.md
  docs/resources/aws_rds_cluster.md
  docs/resources/aws_rds_clusters.md
  docs/resources/aws_redshift_cluster.md
  docs/resources/aws_redshift_clusters.md
  libraries/aws_backend.rb
  libraries/aws_redshift_cluster.rb
  libraries/aws_redshift_clusters.rb
  test/integration/build/aws.tf
  test/integration/build/outputs.tf
  test/integration/configuration/aws_inspec_config.rb
  test/integration/verify/controls/aws_redshift_cluster.rb
  test/integration/verify/controls/aws_redshift_clusters.rb
  test/unit/resources/aws_redshift_cluster_test.rb
  test/unit/resources/aws_redshift_clusters_test.rb
Labels: Documentation, Feature Request, Version: Bump Minor

#342 Soumyo/db parameter groups
  README.md
  docs/resources/aws_db_parameter_group.md
  docs/resources/aws_db_parameter_groups.md
  libraries/aws_db_parameter_group.rb
  libraries/aws_db_parameter_groups.rb
  test/integration/build/aws.tf
  test/integration/build/outputs.tf
  test/integration/configuration/aws_inspec_config.rb
  test/integration/verify/controls/aws_db_parameter_group.rb
  test/integration/verify/controls/aws_db_parameter_groups.rb
  test/integration/verify/controls/aws_db_parameter_groups_loop.rb
  test/unit/resources/aws_db_parameter_group_test.rb
  test/unit/resources/aws_db_parameter_groups_test.rb
Labels: Documentation, Feature Request

#339 Support network ACL(s)
  README.md
  docs/resources/aws_network_acl.md
  docs/resources/aws_network_acls.md
  libraries/aws_network_acl.rb
  libraries/aws_network_acls.rb
  test/integration/build/aws.tf
  test/integration/build/outputs.tf
  test/integration/configuration/aws_inspec_config.rb
  test/integration/verify/controls/aws_network_acl.rb
  test/integration/verify/controls/aws_network_acls.rb
  test/unit/resources/aws_network_acl_test.rb
  test/unit/resources/aws_network_acls_test.rb
  test/unit/resources/mock/aws_network_acl_mock.rb
Labels: Documentation, Feature Request, Version: Bump Minor

#355 Support aws transit gateway route
  README.md
  docs/resources/aws_transit_gateway_route.md
  docs/resources/aws_transit_gateway_routes.md
  libraries/aws_transit_gateway_route.rb
  libraries/aws_transit_gateway_routes.rb
  test/integration/build/aws.tf
  test/integration/build/outputs.tf
  test/integration/configuration/aws_inspec_config.rb
  test/integration/verify/controls/aws_transit_gateway_route.rb
  test/integration/verify/controls/aws_transit_gateway_routes.rb
  test/unit/resources/aws_transit_gateway_route_test.rb
  test/unit/resources/aws_transit_gateway_routes_test.rb
  test/unit/resources/mock/aws_transit_gateway_route_mock.rb
Labels: Documentation, Version: Bump Minor

#336 Ec2 vpc cidr block
  docs/resources/aws_vpc.md
  docs/resources/aws_vpcs.md
  libraries/aws_vpc.rb
  libraries/aws_vpcs.rb
  test/integration/verify/controls/aws_vpc.rb
  test/integration/verify/controls/aws_vpcs.rb
  test/unit/resources/aws_vpc_test.rb
  test/unit/resources/aws_vpcs_test.rb
Labels: Documentation, Feature Request, Version: Bump Minor

#322 Soumyo/ec2 eip resource
  README.md
  docs/resources/aws_ec2_eip.md
  docs/resources/aws_ec2_eips.md
  libraries/aws_ec2_eip.rb
  libraries/aws_ec2_eips.rb
  test/integration/build/aws.tf
  test/integration/build/outputs.tf
  test/integration/verify/controls/aws_ec2_eip.rb
  test/integration/verify/controls/aws_ec2_eips.rb
  test/unit/resources/aws_ec2_eip_test.rb
  test/unit/resources/aws_ec2_eips_test.rb
Labels: Documentation, Version: Bump Minor

#340 Added support for VPC connection notification resource
  README.md
  docs/resources/aws_vpc_endpoint_notification.md
  docs/resources/aws_vpc_endpoint_notifications.md
  libraries/aws_vpc_endpoint_connection_notification.rb
  libraries/aws_vpc_endpoint_connection_notifications.rb
  test/integration/build/aws.tf
  test/integration/build/outputs.tf
  test/integration/configuration/aws_inspec_config.rb
  test/integration/verify/controls/vpc_endpoint_notification.rb
  test/integration/verify/controls/vpc_endpoint_notifications.rb
  test/unit/resources/vpc_endpoint_notification_test.rb
  test/unit/resources/vpc_endpoint_notifications_test.rb
Labels: Documentation, Version: Bump Minor

#346 Soumyo/aws ec2 transit gateway route table association
  docs/resources/aws_ec2_transit_gateway_route_table_association.md
  docs/resources/aws_ec2_transit_gateway_route_table_associations.md
  libraries/aws_ec2_transit_gateway_route_table_association.rb
  libraries/aws_ec2_transit_gateway_route_table_associations.rb
  test/integration/build/aws.tf
  test/integration/build/outputs.tf
  test/integration/verify/controls/aws_ec2_transit_gateway_route_table_association.rb
  test/integration/verify/controls/aws_ec2_transit_gateway_route_table_associations.rb
  test/unit/resources/aws_ec2_transit_gateway_route_table_association_test.rb
  test/unit/resources/aws_ec2_transit_gateway_route_table_associations_test.rb
Labels: Documentation, Feature Request
