Repository inspec/inspec-aws, pull requests merged in 2021-12, with the labels that each got.

#795 Publish release notes 2021-11-30
  docs-chef-io/static/release-notes/inspec-aws/2021-11-30.md
  docs-chef-io/static/release-notes/inspec-aws/release-dates.json
Labels: Documentation

#771 soumyo/aws_rds_db_proxy
  docs/resources/aws_rds_db_proxy.md
  libraries/aws_rds_db_proxy.rb
  test/integration/build/aws.tf
  test/integration/build/outputs.tf
  test/integration/verify/controls/aws_rds_db_proxy.rb
  test/unit/resources/aws_rds_db_proxy_test.rb
Labels: Feature Request, Documentation, Epic, 2021_PQ4, ReadyForDocs

#772 soumyo/aws_rds_db_proxy_endpoint
  docs/resources/aws_rds_db_proxy_endpoint.md
  docs/resources/aws_rds_db_proxy_endpoints.md
  libraries/aws_rds_db_proxy_endpoint.rb
  libraries/aws_rds_db_proxy_endpoints.rb
  test/integration/build/aws.tf
  test/integration/verify/controls/aws_rds_db_proxy_endpoint.rb
  test/integration/verify/controls/aws_rds_db_proxy_endpoints.rb
  test/unit/resources/aws_rds_db_proxy_endpoint_test.rb
  test/unit/resources/aws_rds_db_proxy_endpoints_test.rb
Labels: Feature Request, Documentation, Epic, 2021_PQ4, ReadyForDocs

#782 nirbhay/aws_rds_db_security_group
  docs/resources/aws_rds_db_security_group.md
  docs/resources/aws_rds_db_security_groups.md
  libraries/aws_rds_db_security_group.rb
  libraries/aws_rds_db_security_groups.rb
  test/integration/verify/controls/aws_rds_db_security_group.rb
  test/integration/verify/controls/aws_rds_db_security_groups.rb
  test/unit/resources/aws_rds_db_security_group_test.rb
  test/unit/resources/aws_rds_db_security_groups_test.rb
Labels: Feature Request, Documentation, Epic, 2021_PQ4, ReadyForDocs

#781 nirbhay/aws_rds_event_subscription
  docs/resources/aws_rds_event_subscription.md
  docs/resources/aws_rds_event_subscriptions.md
  libraries/aws_rds_event_subscription.rb
  libraries/aws_rds_event_subscriptions.rb
  test/integration/build/aws.tf
  test/integration/build/outputs.tf
  test/integration/verify/controls/aws_rds_event_subscription.rb
  test/integration/verify/controls/aws_rds_event_subscriptions.rb
  test/unit/resources/aws_rds_event_subscription_test.rb
  test/unit/resources/aws_rds_event_subscriptions_test.rb
Labels: Feature Request, Documentation, Epic, 2021_PQ4, ReadyForDocs

#780 nitbhay/aws_rds_global_cluster
  docs/resources/aws_rds_global_cluster.md
  docs/resources/aws_rds_global_clusters.md
  libraries/aws_rds_global_cluster.rb
  libraries/aws_rds_global_clusters.rb
  test/integration/build/aws.tf
  test/integration/build/outputs.tf
  test/integration/verify/controls/aws_rds_global_cluster.rb
  test/integration/verify/controls/aws_rds_global_clusters.rb
  test/unit/resources/aws_rds_global_cluster_test.rb
  test/unit/resources/aws_rds_global_clusters_test.rb
Labels: Feature Request, Documentation, Epic, 2021_PQ4, ReadyForDocs

#777 soumyo/aws_signer_profile_permission
  docs/resources/aws_signer_profile_permissions.md
  libraries/aws_signer_profile_permissions.rb
  test/integration/build/aws.tf
  test/integration/build/outputs.tf
  test/integration/verify/controls/aws_signer_profile_permissions.rb
  test/unit/resources/aws_signer_profile_permissions_test.rb
Labels: Feature Request, Documentation, Epic, 2021_PQ4, ReadyForDocs

#774 soumyo/aws_lambda_version
  docs/resources/aws_lambda_version.md
  docs/resources/aws_lambda_versions.md
  libraries/aws_lambda_version.rb
  libraries/aws_lambda_versions.rb
  test/integration/build/aws.tf
  test/integration/build/outputs.tf
  test/integration/verify/controls/aws_lambda_version.rb
  test/integration/verify/controls/aws_lambda_versions.rb
  test/unit/resources/aws_lambda_version_test.rb
  test/unit/resources/aws_lambda_versions_test.rb
Labels: Feature Request, Documentation, Epic, 2021_PQ4, ReadyForDocs

#773 soumyo/aws_rds_db_proxy_target_group
  docs/resources/aws_rds_db_proxy_target_group.md
  docs/resources/aws_rds_db_proxy_target_groups.md
  test/integration/build/outputs.tf
  test/integration/verify/controls/aws_rds_db_proxy_target_group.rb
  test/integration/verify/controls/aws_rds_db_proxy_target_groups.rb
Labels: Feature Request, Documentation, Epic, 2021_PQ4, ReadyForDocs

#778 soumyo/update_the_readme_till_nov_26
  README.md
Labels: Do not merge, in progress, wip

#797 Miscellaneous docs fixes
  docs/resources/aws_ami.md
  docs/resources/aws_amis.md
  docs/resources/aws_amplify_branch.md
  docs/resources/aws_amplify_branches.md
  docs/resources/aws_batch_compute_environments.md
  docs/resources/aws_cloudformation_stacks.md
  docs/resources/aws_cloudfront_key_group.md
  docs/resources/aws_cloudwatch_composite_alarm.md
  docs/resources/aws_cloudwatch_dashboard.md
  docs/resources/aws_cloudwatch_dashboards.md
  docs/resources/aws_ec2_launch_templates.md
  docs/resources/aws_ec2_network_interface_permissions.md
  docs/resources/aws_ec2_vpc_peering_connection.md
  docs/resources/aws_elasticloadbalancingv2_target_group.md
  docs/resources/aws_hosted_zone.md
  docs/resources/aws_iam_inline_policy.md
  docs/resources/aws_iam_roles.md
  docs/resources/aws_iam_server_certificate.md
  docs/resources/aws_iam_server_certificates.md
  docs/resources/aws_lambda.md
  docs/resources/aws_lambda_permissions.md
  docs/resources/aws_lambdas.md
  docs/resources/aws_mq_brokers.md
  docs/resources/aws_mq_configurations.md
  docs/resources/aws_network_acl.md
  docs/resources/aws_network_acls.md
  docs/resources/aws_organizations_member.md
  docs/resources/aws_rds_cluster.md
  docs/resources/aws_s3_access_point.md
  docs/resources/aws_s3_access_points.md
  docs/resources/aws_transit_gateway.md
  docs/resources/aws_transit_gateway_route.md
  docs/resources/aws_transit_gateway_routes.md
  docs/resources/aws_vpc.md
  docs/resources/aws_vpc_endpoint.md
  docs/resources/aws_vpc_endpoint_notification.md
  docs/resources/aws_vpc_endpoint_notifications.md
  docs/resources/aws_vpcs.md
Labels: Documentation

#770 Feature request for CloudFormation Template
  docs/resources/aws_cloudformation_template.md
  libraries/aws_cloudformation_template.rb
Labels: CFT Support

#799 Fix resource name in docs
  docs/resources/aws_ec2_vpn_gateway_route_propagations.md
Labels: Documentation

#783 nirbhay/aws_s3_bucket_policy
  README.md
  docs/resources/aws_s3_bucket_policy.md
  libraries/aws_s3_bucket_policy.rb
  test/integration/build/aws.tf
  test/integration/build/outputs.tf
  test/integration/verify/controls/aws_s3_bucket_policy.rb
  test/unit/resources/aws_s3_bucket_policy_test.rb
Labels: Feature Request, Documentation, Epic, 2021_PQ4, ReadyForDocs

#802 nirbhay/aws_waf_rule
  docs/resources/aws_waf_rule.md
  docs/resources/aws_waf_rules.md
  libraries/aws_waf_rule.rb
  libraries/aws_waf_rules.rb
  test/integration/verify/controls/aws_waf_rule.rb
  test/integration/verify/controls/aws_waf_rules.rb
  test/unit/resources/aws_waf_rule_test.rb
  test/unit/resources/aws_waf_rules_test.rb
Labels: Feature Request, Documentation, Epic, 2021_PQ4, ReadyForDocs

#816 Fixed build failing because of Activesupport library for ruby 2.6
  Gemfile
Labels: Version: Bump Minor

#803 nirbhay/aws_waf_byte_match_set
  docs/resources/aws_waf_byte_match_set.md
  docs/resources/aws_waf_byte_match_sets.md
  libraries/aws_waf_byte_match_set.rb
  libraries/aws_waf_byte_match_sets.rb
  test/integration/verify/controls/aws_waf_byte_match_set.rb
  test/integration/verify/controls/aws_waf_byte_match_sets.rb
  test/unit/resources/aws_waf_byte_match_set_test.rb
  test/unit/resources/aws_waf_byte_match_sets_test.rb
Labels: Feature Request, Documentation, Epic, 2021_PQ4, ReadyForDocs

#807 nirbhay/aws_waf_xss_match_set
  docs/resources/aws_waf_xss_match_match_set.md
  docs/resources/aws_waf_xss_match_match_sets.md
  libraries/aws_waf_xss_match_set.rb
  libraries/aws_waf_xss_match_sets.rb
  test/integration/verify/controls/aws_waf_xss_match_match_set.rb
  test/integration/verify/controls/aws_waf_xss_match_match_sets.rb
  test/unit/resources/aws_waf_xss_match_set_test.rb
  test/unit/resources/aws_waf_xss_match_sets_test.rb
Labels: Feature Request, Documentation, Epic, 2021_PQ4, ReadyForDocs

#806 nirbhay/aws_waf_sql_injection_match_set
  docs/resources/aws_waf_sql_injection_match_set.md
  docs/resources/aws_waf_sql_injection_match_sets.md
  libraries/aws_waf_sql_injection_match_set.rb
  libraries/aws_waf_sql_injection_match_sets.rb
  test/integration/verify/controls/aws_waf_sql_injection_match_set.rb
  test/integration/verify/controls/aws_waf_sql_injection_match_sets.rb
  test/unit/resources/aws_waf_sql_injection_match_set_test.rb
  test/unit/resources/aws_waf_sql_injection_match_sets_test.rb
Labels: Feature Request, Documentation, Epic, 2021_PQ4, ReadyForDocs

#805 nirbhay/aws_waf_size_constraint_set
  docs/resources/aws_waf_size_constraint_set.md
  docs/resources/aws_waf_size_constraint_sets.md
  libraries/aws_waf_size_constraint_set.rb
  libraries/aws_waf_size_constraint_sets.rb
  test/integration/verify/controls/aws_waf_size_constraint_set.rb
  test/integration/verify/controls/aws_waf_size_constraint_sets.rb
  test/unit/resources/aws_waf_size_constraint_set_test.rb
  test/unit/resources/aws_waf_size_constraint_sets_test.rb
Labels: Feature Request, Documentation, Epic, 2021_PQ4, ReadyForDocs

#804 nirbhay/aws_waf_ip_set
  docs/resources/aws_waf_ip_set.md
  docs/resources/aws_waf_ip_sets.md
  libraries/aws_waf_ip_set.rb
  libraries/aws_waf_ip_sets.rb
  test/integration/verify/controls/aws_waf_ip_set.rb
  test/integration/verify/controls/aws_waf_ip_sets.rb
  test/unit/resources/aws_waf_ip_set_test.rb
  test/unit/resources/aws_waf_ip_sets_test.rb
Labels: Feature Request, Documentation, Epic, 2021_PQ4, ReadyForDocs

#798 soumyo/aws_ssm_maintenance_window
  docs/resources/aws_ssm_maintenance_window.md
  docs/resources/aws_ssm_maintenance_windows.md
  libraries/aws_ssm_maintenance_window.rb
  libraries/aws_ssm_maintenance_windows.rb
  test/integration/build/aws.tf
  test/integration/build/outputs.tf
  test/integration/verify/controls/aws_ssm_maintenance_window.rb
  test/integration/verify/controls/aws_ssm_maintenance_windows.rb
  test/unit/resources/aws_ssm_maintenance_window_test.rb
  test/unit/resources/aws_ssm_maintenance_windows_test.rb
Labels: Feature Request, Documentation, Epic, 2021_PQ4, ReadyForDocs
