Repository inspec/inspec-aws, pull requests merged in 2021-11, with the labels that each got.

#699 added changes for AWS alb access log enabled property
  docs/resources/aws_alb.md
  libraries/aws_alb.rb
  test/integration/build/aws.tf
  test/integration/verify/controls/aws_alb.rb
  test/unit/resources/aws_alb_test.rb
  test/unit/resources/mock/aws_alb_mock.rb
Labels: Documentation, CFT Support, 2021_PQ4, ReadyForDocs

#700 adding api gateway stage resource
  docs/resources/aws_api_gateway_stage.md
  docs/resources/aws_api_gateway_stages.md
  libraries/aws_api_gateway_stage.rb
  libraries/aws_api_gateway_stages.rb
  test/integration/build/aws.tf
  test/integration/build/outputs.tf
  test/integration/verify/controls/aws_api_gateway_stage.rb
  test/integration/verify/controls/aws_api_gateway_stages.rb
  test/unit/resources/aws_api_gateway_stage_test.rb
  test/unit/resources/aws_api_gateway_stages_test.rb
Labels: Documentation, CFT Support, 2021_PQ4, ReadyForDocs

#504 AWS IAM Managed policy resource
  docs/resources/aws_iam_managed_policies.md
  docs/resources/aws_iam_managed_policy.md
  libraries/aws_iam_managed_policies.rb
  libraries/aws_iam_managed_policy.rb
  test/integration/verify/controls/aws_iam_managed_policies.rb
  test/integration/verify/controls/aws_iam_managed_policy.rb
  test/unit/resources/aws_iam_managed_policies_test.rb
  test/unit/resources/aws_iam_managed_policy_test.rb
Labels: Feature Request, Documentation, Epic, ReadyForDocs

#636 Nirbhay/MQConfigurations
  docs/resources/aws_mq_configuration.md
  docs/resources/aws_mq_configurations.md
  libraries/aws_backend.rb
  libraries/aws_mq_configuration.rb
  libraries/aws_mq_configurations.rb
  test/integration/build/files/localhost.key
  test/integration/build/outputs.tf
  test/integration/verify/controls/aws_mq_configuration.rb
  test/integration/verify/controls/aws_mq_configurations.rb
  test/unit/resources/aws_mq_configuration_test.rb
  test/unit/resources/aws_mq_configurations_test.rb
Labels: Feature Request, Documentation, 2021_PQ4, ReadyForDocs

#631 soumyo/Adding the Missing Docs in the Readme.md
  README.md
Labels: Feature Request, Documentation

#752 Fix release notes dates file
  docs-chef-io/static/release-notes/inspec-aws/release-dates.json
Labels: Documentation

#695 soumyo/aws_iam_ssh_public_key
  docs/resources/aws_iam_ssh_public_key.md
  docs/resources/aws_iam_ssh_public_keys.md
  libraries/aws_iam_ssh_public_key.rb
  libraries/aws_iam_ssh_public_keys.rb
  test/integration/verify/controls/aws_iam_ssh_public_key.rb
  test/integration/verify/controls/aws_iam_ssh_public_keys.rb
  test/unit/resources/aws_iam_ssh_public_key_test.rb
  test/unit/resources/aws_iam_ssh_public_keys_test.rb
Labels: Feature Request, Documentation, Epic, CFT Support, 2021_PQ4, ReadyForDocs

#684 Nirbhay/AWSCloudWatchLogsStreams
  docs/resources/aws_cloudwatchlogs_log_stream.md
  docs/resources/aws_cloudwatchlogs_log_streams.md
  libraries/aws_cloudwatchlogs_log_stream.rb
  libraries/aws_cloudwatchlogs_log_streams.rb
  test/integration/build/aws.tf
  test/integration/build/outputs.tf
  test/integration/verify/controls/aws_cloudwatchlogs_log_stream.rb
  test/integration/verify/controls/aws_cloudwatchlogs_log_streams.rb
  test/unit/resources/aws_cloudwatchlogs_log_stream_test.rb
  test/unit/resources/aws_cloudwatchlogs_log_streams_test.rb
Labels: Feature Request, Documentation, Epic, 2021_PQ4, ReadyForDocs

#686 Nirbhay/EC2-Carrier-Gateway
  docs/resources/aws_ec2_carrier_gateway.md
  docs/resources/aws_ec2_carrier_gateways.md
  libraries/aws_ec2_carrier_gateway.rb
  libraries/aws_ec2_carrier_gateways.rb
  test/integration/verify/controls/aws_ec2_carrier_gateway.rb
  test/integration/verify/controls/aws_ec2_carrier_gateways.rb
  test/unit/resources/aws_ec2_carrier_gateway_test.rb
  test/unit/resources/aws_ec2_carrier_gateways_test.rb
Labels: Feature Request, Documentation, Epic, 2021_PQ4, ReadyForDocs

#685 Nirbhay/AWS_Logs_Subscription_Filter
  docs/resources/aws_cloudwatchlogs_subscription_filter.md
  docs/resources/aws_cloudwatchlogs_subscription_filters.md
  libraries/aws_cloudwatchlogs_subscription_filter.rb
  libraries/aws_cloudwatchlogs_subscription_filters.rb
  test/integration/verify/controls/aws_cloudwatchlogs_subscription_filter.rb
  test/integration/verify/controls/aws_cloudwatchlogs_subscription_filters.rb
  test/unit/resources/aws_cloudwatchlogs_subscription_filter_test.rb
  test/unit/resources/aws_cloudwatchlogs_subscription_filters_test.rb
Labels: Feature Request, Documentation, 2021_PQ4, ReadyForDocs

#750 Added support for checking last_status for a config recorder
  docs/resources/aws_config_recorder.md
  libraries/aws_config_recorder.rb
  test/integration/build/aws.tf
  test/integration/verify/controls/aws_config_recorder.rb
  test/unit/resources/aws_config_recorder_test.rb
Labels: Feature Request, Documentation, CFT Support, 2021_PQ4, ReadyForDocs

#759 Minor docs fixes
  docs/resources/aws_ec2_client_vpn_target_network_association.md
  docs/resources/aws_ec2_network_interface_permission.md
  docs/resources/aws_mq_broker.md
  docs/resources/aws_mq_brokers.md
  docs/resources/aws_mq_configuration.md
  docs/resources/aws_mq_configurations.md
  docs/resources/aws_rds_db_cluster_snapshots.md
Labels: Documentation

#663 soumyo/aws_ec2_capacity_reservation
  docs/resources/aws_ec2_capacity_reservation.md
  docs/resources/aws_ec2_capacity_reservations.md
  libraries/aws_ec2_capacity_reservation.rb
  libraries/aws_ec2_capacity_reservations.rb
  test/integration/build/aws.tf
  test/integration/build/outputs.tf
  test/integration/verify/controls/aws_ec2_capacity_reservation.rb
  test/integration/verify/controls/aws_ec2_capacity_reservations.rb
  test/unit/resources/aws_ec2_capacity_reservation_test.rb
  test/unit/resources/aws_ec2_capacity_reservations_test.rb
Labels: Feature Request, Documentation, Epic, 2021_PQ4, ReadyForDocs

#664 soumyo/aws_ec2_customer_gateway
  docs/resources/aws_ec2_customer_gateway.md
  docs/resources/aws_ec2_customer_gateways.md
  libraries/aws_ec2_customer_gateway.rb
  libraries/aws_ec2_customer_gateways.rb
  test/integration/build/aws.tf
  test/integration/build/outputs.tf
  test/integration/verify/controls/aws_ec2_customer_gateway.rb
  test/integration/verify/controls/aws_ec2_customer_gateways.rb
  test/unit/resources/aws_ec2_customer_gateway_test.rb
  test/unit/resources/aws_ec2_customer_gateways_test.rb
Labels: Feature Request, Documentation, Epic, 2021_PQ4, ReadyForDocs

#753 soumyo/aws_cloudformation_template
  docs/resources/aws_cloudformation_template.md
  libraries/aws_cloudformation_template.rb
  test/integration/verify/controls/aws_cloudformation_tempate.rb
  test/unit/resources/aws_cloudformation_template_test.rb
Labels: Feature Request, Documentation, CFT Support, 2021_PQ4, ReadyForDocs

#637 Nirbhay/AmplifyApp
  docs/resources/aws_amplify_app.md
  docs/resources/aws_amplify_apps.md
  libraries/aws_amplify_app.rb
  libraries/aws_amplify_apps.rb
  libraries/aws_backend.rb
  test/integration/build/aws.tf
  test/integration/build/outputs.tf
  test/integration/verify/controls/aws_amplify_app.rb
  test/integration/verify/controls/aws_amplify_apps.rb
  test/unit/resources/aws_amplify_app_test.rb
  test/unit/resources/aws_amplify_apps_test.rb
Labels: Documentation, ReadyForDocs

#630 soumyo/aws_network_firewall_firewall_policy
  docs/resources/aws_network_firewall_firewall_policies.md
  docs/resources/aws_network_firewall_firewall_policy.md
  libraries/aws_backend.rb
  libraries/aws_network_firewall_firewall_policies.rb
  libraries/aws_network_firewall_firewall_policy.rb
  test/integration/verify/controls/aws_network_firewall_firewall_policies.rb
  test/integration/verify/controls/aws_network_firewall_firewall_policy.rb
Labels: Feature Request, Documentation, Epic, ReadyForDocs

#628 soumyo/aws_network_manager_customer_gateway_association
  docs/resources/aws_network_manager_customer_gateway_association.md
  docs/resources/aws_network_manager_customer_gateway_associations.md
  libraries/aws_network_manager_customer_gateway_association.rb
  libraries/aws_network_manager_customer_gateway_associations.rb
  test/integration/verify/controls/aws_network_manager_customer_gateway_association.rb
  test/integration/verify/controls/aws_network_manager_customer_gateway_associations.rb
  test/unit/resources/aws_network_manager_customer_gateway_association_test.rb
  test/unit/resources/aws_network_manager_customer_gateway_associations_test.rb
Labels: Feature Request, Documentation, Epic, ReadyForDocs

#627 soumyo/aws_network_firewall_rule_group
  docs/resources/aws_network_firewall_rule_group.md
  docs/resources/aws_network_firewall_rule_groups.md
  libraries/aws_network_firewall_rule_group.rb
  libraries/aws_network_firewall_rule_groups.rb
  test/integration/verify/controls/aws_network_firewall_rule_group.rb
  test/integration/verify/controls/aws_network_firewall_rule_groups.rb
  test/unit/resources/aws_network_firewall_rule_group_test.rb
  test/unit/resources/aws_network_firewall_rule_groups_test.rb
Labels: Feature Request, Documentation, Epic, ReadyForDocs

#626 soumyo/aws_network_firewall_logging_configuration
  docs/resources/aws_network_firewall_logging_configuration.md
  libraries/aws_backend.rb
  libraries/aws_network_firewall_logging_configuration.rb
  test/integration/verify/controls/aws_network_firewall_logging_configuration.rb
  test/unit/resources/aws_network_firewall_logging_configuration_test.rb
Labels: Feature Request, Documentation, Epic, ReadyForDocs

#625 soumyo/aws_network_firewall_firewall
  docs/resources/aws_network_firewall_firewall.md
  docs/resources/aws_network_firewall_firewalls.md
  libraries/aws_network_firewall_firewall.rb
  libraries/aws_network_firewall_firewalls.rb
  test/integration/build/aws.tf
  test/integration/build/outputs.tf
  test/integration/verify/controls/aws_network_firewall_firewall.rb
  test/integration/verify/controls/aws_network_firewall_firewalls.rb
  test/unit/resources/aws_network_firewall_firewall_test.rb
  test/unit/resources/aws_network_firewall_firewalls_test.rb
Labels: Feature Request, Documentation, Epic, ReadyForDocs

#624 soumyo/aws_ec2_spot_fleet
  docs/resources/aws_ec2_spot_fleet.md
  docs/resources/aws_ec2_spot_fleets.md
  libraries/aws_ec2_spot_fleet.rb
  libraries/aws_ec2_spot_fleets.rb
  test/integration/build/aws.tf
  test/integration/build/outputs.tf
  test/integration/verify/controls/aws_ec2_spot_fleet.rb
  test/integration/verify/controls/aws_ec2_spot_fleets.rb
  test/unit/resources/aws_ec2_spot_fleet_test.rb
  test/unit/resources/aws_ec2_spot_fleets_test.rb
Labels: Feature Request, Documentation, Epic, ReadyForDocs

#638 Nirbhay/AmplifyBranch
  docs/resources/aws_amplify_branch.md
  docs/resources/aws_amplify_branches.md
  libraries/aws_amplify_branch.rb
  libraries/aws_amplify_branches.rb
  test/integration/build/aws.tf
  test/integration/build/outputs.tf
  test/integration/verify/controls/aws_amplify_branch.rb
  test/integration/verify/controls/aws_amplify_branches.rb
  test/unit/resources/aws_amplify_branch_test.rb
  test/unit/resources/aws_amplify_branches_test.rb
Labels: Documentation, ReadyForDocs

#654 Adding support for SDB Resource
  docs/resources/aws_sdb_domains.md
  libraries/aws_backend.rb
  libraries/aws_sdb_domains.rb
  test/integration/build/aws.tf
  test/integration/build/outputs.tf
  test/integration/verify/controls/aws_sdb_domains.rb
  test/unit/resources/aws_sdb_domains_test.rb
Labels: Feature Request, Documentation, Epic, 2021_PQ4, ReadyForDocs

#766 Added support for AWS::EMR::SecurityConfiguration.
  docs/resources/aws_emr_security_configuration.md
  docs/resources/aws_emr_security_configurations.md
  libraries/aws_backend.rb
  libraries/aws_emr_security_configuration.rb
  libraries/aws_emr_security_configurations.rb
  test/integration/build/outputs.tf
  test/integration/configuration/aws_inspec_config.rb
  test/integration/verify/controls/aws_emr_security_configuration.rb
  test/integration/verify/controls/aws_emr_security_configurations.rb
  test/unit/resources/aws_emr_security_configuration_test.rb
  test/unit/resources/aws_emr_security_configurations_test.rb
  test/unit/resources/mock/aws_emr_security_configuration_mock.rb
Labels: Feature Request, Documentation, CFT Support, 2021_PQ4, ReadyForDocs

#758 Added support for AWS EMR Cluster resource
  docs/resources/aws_emr_cluster.md
  docs/resources/aws_emr_clusters.md
  libraries/aws_emr_cluster.rb
  libraries/aws_emr_clusters.rb
  test/integration/build/aws.tf
  test/integration/build/outputs.tf
  test/integration/configuration/aws_inspec_config.rb
  test/integration/verify/controls/aws_emr_cluster.rb
  test/integration/verify/controls/aws_emr_clusters.rb
  test/unit/resources/aws_emr_cluster_test.rb
  test/unit/resources/aws_emr_clusters_test.rb
  test/unit/resources/mock/aws_emr_mock.rb
Labels: Feature Request, Documentation, CFT Support, 2021_PQ4, ReadyForDocs

#682 Nirbhay/AWS CloudFront Public Key resource
  docs/resources/aws_cloudfront_public_key.md
  docs/resources/aws_cloudfront_public_keys.md
  libraries/aws_cloudfront_public_key.rb
  libraries/aws_cloudfront_public_keys.rb
  test/integration/build/aws.tf
  test/integration/build/files/pubkey.pem
  test/integration/build/outputs.tf
  test/integration/verify/controls/aws_cloudfront_public_key.rb
  test/integration/verify/controls/aws_cloudfront_public_keys.rb
  test/unit/resources/aws_cloudfront_public_key_test.rb
  test/unit/resources/aws_cloudfront_public_keys_test.rb
Labels: Feature Request, Documentation, 2021_PQ4, ReadyForDocs

#679 Nirbhay/CloudFront Key Group
  docs/resources/aws_cloudfront_key_group.md
  docs/resources/aws_cloudfront_key_groups.md
  libraries/aws_cloudfront_key_group.rb
  libraries/aws_cloudfront_key_groups.rb
  test/integration/build/aws.tf
  test/integration/build/outputs.tf
  test/integration/verify/controls/aws_cloudfront_key_group.rb
  test/integration/verify/controls/aws_cloudfront_key_groups.rb
  test/unit/resources/aws_cloudfront_key_group_test.rb
  test/unit/resources/aws_cloudfront_key_groups_test.rb
Labels: Feature Request, Documentation, Epic, 2021_PQ4, ReadyForDocs

#676 soumyo/aws_cloudwatch_composite_alarm
  docs/resources/aws_cloudwatch_composite_alarm.md
  docs/resources/aws_cloudwatch_composite_alarms.md
  libraries/aws_cloudwatch_composite_alarm.rb
  libraries/aws_cloudwatch_composite_alarms.rb
  test/integration/build/aws.tf
  test/integration/verify/controls/aws_cloudwatch_composite_alarm.rb
  test/integration/verify/controls/aws_cloudwatch_composite_alarms.rb
  test/unit/resources/aws_cloudwatch_composite_alarm_test.rb
  test/unit/resources/aws_cloudwatch_composite_alarms_test.rb
Labels: Feature Request, Documentation, Epic, 2021_PQ4, ReadyForDocs

#674 soumyo/aws_cloudfront_streaming_distribution
  docs/resources/aws_cloudfront_streaming_distribution.md
  docs/resources/aws_cloudfront_streaming_distributions.md
  libraries/aws_cloudfront_streaming_distribution.rb
  libraries/aws_cloudfront_streaming_distributions.rb
  test/integration/build/aws.tf
  test/integration/build/outputs.tf
  test/integration/verify/controls/aws_cloudfront_streaming_distribution.rb
  test/integration/verify/controls/aws_cloudfront_streaming_distributions.rb
  test/unit/resources/aws_cloudfront_streaming_distribution_test.rb
  test/unit/resources/aws_cloudfront_streaming_distributions_test.rb
Labels: Feature Request, Documentation, Epic, 2021_PQ4, ReadyForDocs

#657 Added support for Cloud watch metric stream
  docs/resources/aws_cloudwatch_metric_stream.md
  docs/resources/aws_cloudwatch_metric_streams.md
  libraries/aws_cloudwatch_metric_stream.rb
  libraries/aws_cloudwatch_metric_streams.rb
  test/integration/build/aws.tf
  test/integration/build/outputs.tf
  test/integration/verify/controls/aws_cloudwatch_metric_stream.rb
  test/integration/verify/controls/aws_cloudwatch_metric_streams.rb
  test/unit/resources/aws_cloudwatch_metric_stream_test.rb
  test/unit/resources/aws_cloudwatch_metric_streams_test.rb
Labels: Feature Request, Documentation, Epic, 2021_PQ4, ReadyForDocs

#673 soumyo/aws_cloudfront_realtime_log_config
  docs/resources/aws_cloudfront_realtime_log_config.md
  docs/resources/aws_cloudfront_realtime_log_configs.md
  libraries/aws_cloudfront_realtime_log_config.rb
  libraries/aws_cloudfront_realtime_log_configs.rb
  test/integration/build/aws.tf
  test/integration/build/outputs.tf
  test/integration/verify/controls/aws_cloudfront_realtime_log_config.rb
  test/integration/verify/controls/aws_cloudfront_realtime_log_configs.rb
  test/unit/resources/aws_cloudfront_realtime_log_config_test.rb
  test/unit/resources/aws_cloudfront_realtime_log_configs_test.rb
Labels: Feature Request, Documentation, Epic, 2021_PQ4, ReadyForDocs

#671 soumyo/aws_lambda_layer_version_permission
  docs/resources/aws_lambda_layer_version_permission.md
  libraries/aws_lambda_layer_version_permission.rb
  test/integration/verify/controls/aws_lambda_layer_version_permission.rb
  test/unit/resources/aws_lambda_layer_version_permission_test.rb
Labels: Feature Request, Documentation, Epic, 2021_PQ4, ReadyForDocs

#659 Added Support for Insight Rules
  docs/resources/aws_cloudwatch_insight_rules.md
  libraries/aws_cloudwatch_insight_rules.rb
  test/integration/verify/controls/aws_cloudwatch_insight_rules.rb
  test/unit/resources/aws_cloudwatch_insight_rules_test.rb
Labels: Feature Request, Documentation, Epic, 2021_PQ4, ReadyForDocs

#660 added audit support for s3 access points
  docs/resources/aws_s3_access_point.md
  docs/resources/aws_s3_access_points.md
  libraries/aws_s3_access_point.rb
  libraries/aws_s3_access_points.rb
  test/integration/verify/controls/aws_s3_access_point.rb
  test/integration/verify/controls/aws_s3_access_points.rb
  test/unit/resources/aws_s3_access_point_test.rb
  test/unit/resources/aws_s3_access_points_test.rb
Labels: Feature Request, Documentation, Epic, 2021_PQ4, ReadyForDocs

#666 soumyo/aws_ec2_eip_association
  docs/resources/aws_ec2_eip_association.md
  docs/resources/aws_ec2_eip_associations.md
  libraries/aws_ec2_eip_association.rb
  libraries/aws_ec2_eip_associations.rb
  test/integration/build/outputs.tf
  test/integration/verify/controls/aws_ec2_eip_association.rb
  test/integration/verify/controls/aws_ec2_eip_associations.rb
  test/unit/resources/aws_ec2_eip_association_test.rb
  test/unit/resources/aws_ec2_eip_associations_test.rb
Labels: Feature Request, Documentation, Epic, 2021_PQ4, ReadyForDocs

#665 soumyo/aws_ec2_egress_only_internet_gateway
  docs/resources/aws_ec2_egress_only_internet_gateway.md
  docs/resources/aws_ec2_egress_only_internet_gateways.md
  libraries/aws_ec2_egress_only_internet_gateway.rb
  libraries/aws_ec2_egress_only_internet_gateways.rb
  test/integration/build/aws.tf
  test/integration/build/outputs.tf
  test/integration/verify/controls/aws_ec2_egress_only_internet_gateway.rb
  test/integration/verify/controls/aws_ec2_egress_only_internet_gateways.rb
  test/unit/resources/aws_ec2_egress_only_internet_gateway_test.rb
  test/unit/resources/aws_ec2_egress_only_internet_gateways_test.rb
Labels: Feature Request, Documentation, Epic, 2021_PQ4, ReadyForDocs

#667 soumyo/aws_ec2_fleet
  docs/resources/aws_ec2_fleet.md
  docs/resources/aws_ec2_fleets.md
  libraries/aws_ec2_fleet.rb
  libraries/aws_ec2_fleets.rb
  test/integration/build/aws.tf
  test/integration/build/outputs.tf
  test/integration/verify/controls/aws_ec2_fleet.rb
  test/integration/verify/controls/aws_ec2_fleets.rb
  test/unit/resources/aws_ec2_fleet_test.rb
  test/unit/resources/aws_ec2_fleets_test.rb
Labels: Feature Request, Documentation, Epic, 2021_PQ4, ReadyForDocs

#668 soumyo/aws_ec2_host
  docs/resources/aws_ec2_host.md
  docs/resources/aws_ec2_hosts.md
  libraries/aws_ec2_host.rb
  libraries/aws_ec2_hosts.rb
  test/integration/verify/controls/aws_ec2_host.rb
  test/integration/verify/controls/aws_ec2_hosts.rb
  test/unit/resources/aws_ec2_host_test.rb
  test/unit/resources/aws_ec2_hosts_test.rb
Labels: Feature Request, Documentation, Epic, 2021_PQ4, ReadyForDocs

#669 soumyo/aws_ec2_placement_group
  docs/resources/aws_ec2_placement_group.md
  docs/resources/aws_ec2_placement_groups.md
  libraries/aws_ec2_placement_group.rb
  libraries/aws_ec2_placement_groups.rb
  test/integration/build/aws.tf
  test/integration/build/outputs.tf
  test/integration/verify/controls/aws_ec2_placement_group.rb
  test/integration/verify/controls/aws_ec2_placement_groups.rb
  test/unit/resources/aws_ec2_placement_group_test.rb
  test/unit/resources/aws_ec2_placement_groups_test.rb
Labels: Feature Request, Documentation, Epic, 2021_PQ4, ReadyForDocs

#747 Nirbhay/AWS_SecurityHub_Hub
  docs/resources/aws_securityhub_hub.md
  libraries/aws_backend.rb
  libraries/aws_securityhub_hub.rb
  test/integration/verify/controls/aws_securityhub_hub.rb
  test/unit/resources/aws_securityhub_hub_test.rb
Labels: Feature Request, Documentation, 2021_PQ4, ReadyForDocs

#748 updated the readme file till NOV_12
  README.md
Labels: 2021_PQ4

#683 CloudWatch Logs Destinantion
  docs/resources/aws_cloudwatchlogs_destination.md
  docs/resources/aws_cloudwatchlogs_destinations.md
  libraries/aws_cloudwatchlogs_destinantion.rb
  libraries/aws_cloudwatchlogs_destinantions.rb
  test/integration/verify/controls/aws_cloudwatchlogs_destinantion.rb
  test/integration/verify/controls/aws_cloudwatchlogs_destinantions.rb
  test/unit/resources/aws_cloudwatchlogs_destinantion_test.rb
  test/unit/resources/aws_cloudwatchlogs_destinantions_test.rb
Labels: Feature Request, Documentation, Epic, 2021_PQ4, ReadyForDocs

#716 NIRBHAY/aws_ec2_client_vpn_route
  docs/resources/aws_ec2_client_vpn_route.md
  docs/resources/aws_ec2_client_vpn_routes.md
  libraries/aws_ec2_client_vpn_route.rb
  libraries/aws_ec2_client_vpn_routes.rb
  test/integration/verify/controls/aws_ec2_client_vpn_route.rb
  test/integration/verify/controls/aws_ec2_client_vpn_routes.rb
  test/unit/resources/aws_ec2_client_vpn_route_test.rb
  test/unit/resources/aws_ec2_client_vpn_routes_test.rb
Labels: Feature Request, Documentation, Epic, 2021_PQ4, ReadyForDocs

#776 soumyo/aws_lambda_code_signing_config
  docs/resources/aws_lambda_code_signing_config.md
  docs/resources/aws_lambda_code_signing_configs.md
  libraries/aws_lambda_code_signing_config.rb
  libraries/aws_lambda_code_signing_configs.rb
  test/integration/build/aws.tf
  test/integration/build/outputs.tf
  test/integration/verify/controls/aws_lambda_code_signing_config.rb
  test/integration/verify/controls/aws_lambda_code_signing_configs.rb
  test/unit/resources/aws_lambda_code_signing_config_test.rb
  test/unit/resources/aws_lambda_code_signing_configs_test.rb
Labels: Feature Request, Documentation, Epic, 2021_PQ4, ReadyForDocs

#672 soumyo/aws_lambda_event_invoke_config
  docs/resources/aws_lambda_event_invoke_config.md
  docs/resources/aws_lambda_event_invoke_configs.md
  libraries/aws_lambda_event_invoke_config.rb
  libraries/aws_lambda_event_invoke_configs.rb
Labels: Feature Request, Epic, 2021_PQ4

#754 soumyo/aws_ses_receipt_rule
  docs/resources/aws_ses_receipt_rule.md
  libraries/aws_backend.rb
  libraries/aws_ses_receipt_rule.rb
  test/integration/build/aws.tf
  test/integration/build/outputs.tf
  test/integration/verify/controls/aws_ses_receipt_rule.rb
  test/unit/resources/aws_ses_receipt_rule_test.rb
Labels: Feature Request, Documentation, Epic, 2021_PQ4, ReadyForDocs

#756 soumyo/aws_ses_template
  docs/resources/aws_ses_template.md
  docs/resources/aws_ses_templates.md
  libraries/aws_ses_template.rb
  libraries/aws_ses_templates.rb
  test/integration/build/aws.tf
  test/integration/build/outputs.tf
  test/integration/verify/controls/aws_ses_template.rb
  test/integration/verify/controls/aws_ses_templates.rb
  test/unit/resources/aws_ses_template_test.rb
  test/unit/resources/aws_ses_templates_test.rb
Labels: Feature Request, Documentation, Epic, 2021_PQ4, ReadyForDocs

#755 soumyo/aws_ses_receipt_rule_set
  docs/resources/aws_ses_receipt_rule_set.md
  docs/resources/aws_ses_receipt_rule_sets.md
  libraries/aws_ses_receipt_rule_set.rb
  libraries/aws_ses_receipt_rule_sets.rb
  test/integration/verify/controls/aws_ses_receipt_rule_set.rb
  test/integration/verify/controls/aws_ses_receipt_rule_sets.rb
  test/unit/resources/aws_ses_receipt_rule_set_test.rb
  test/unit/resources/aws_ses_receipt_rule_sets_test.rb
Labels: Feature Request, Documentation, Epic, 2021_PQ4, ReadyForDocs

#775 soumyo/aws_lambda_alias
  docs/resources/aws_lambda_alias.md
  docs/resources/aws_lambda_aliases.md
  libraries/aws_lambda_alias.rb
  libraries/aws_lambda_aliases.rb
  test/integration/build/aws.tf
  test/integration/build/outputs.tf
  test/integration/verify/controls/aws_lambda_alias.rb
  test/integration/verify/controls/aws_lambda_aliases.rb
  test/unit/resources/aws_lambda_alias_test.rb
  test/unit/resources/aws_lambda_aliases_test.rb
Labels: Feature Request, Documentation, Epic, 2021_PQ4, ReadyForDocs

#537 Nirbhay/ Network Manager Device
  docs/resources/aws_network_manager_device.md
  docs/resources/aws_network_manager_devices.md
  libraries/aws_ec2_network_interface_permission.rb
  libraries/aws_ec2_network_interface_permissions.rb
  libraries/aws_network_manager_device.rb
  libraries/aws_network_manager_devices.rb
  test/integration/verify/controls/aws_ec2_network_manager_device.rb
  test/integration/verify/controls/aws_ec2_network_manager_devices.rb
  test/unit/resources/aws_ec2_network_interface_permission_test.rb
  test/unit/resources/aws_ec2_network_interface_permissions_test.rb
  test/unit/resources/aws_ec2_prefix_lists_test.rb
  test/unit/resources/aws_network_manager_device_test.rb
  test/unit/resources/aws_network_manager_devices_test.rb
Labels: Feature Request, Documentation, Epic, 2021_PQ4, ReadyForDocs
