Repository inspec/inspec-aws, pull requests merged in 2021-07, with the labels that each got.

#479 Need changes in the Readme.md file
  README.md
  docs/resources/aws_db_parameter_group.md
Labels: Documentation

#426 aws_api_gateway_deployment
  docs/resources/aws_api_gateway_deployment.md
  docs/resources/aws_api_gateway_deployments.md
  libraries/aws_api_gateway_deployment.rb
  libraries/aws_api_gateway_deployments.rb
  test/integration/build/aws.tf
  test/integration/verify/controls/aws_api_gateway_deployment.rb
  test/integration/verify/controls/aws_api_gateway_deployments.rb
  test/unit/resources/aws_api_gateway_deployment_test.rb
  test/unit/resources/aws_api_gateway_deployments_test.rb
Labels: Documentation, Epic, Feature Request

#428 aws_api_gateway_restapi
  docs/resources/aws_api_gateway_restapi.md
  docs/resources/aws_api_gateway_restapis.md
  libraries/aws_api_gateway_method.rb
  libraries/aws_api_gateway_restapi.rb
  libraries/aws_api_gateway_restapis.rb
  libraries/aws_backend.rb
  test/integration/verify/controls/aws_api_gateway_restapi.rb
  test/integration/verify/controls/aws_api_gateway_restapis.rb
  test/unit/resources/aws_api_gateway_restapi_test.rb
  test/unit/resources/aws_api_gateway_restapis_test.rb
Labels: Documentation, Epic, Feature Request

#421 aws dms endpoint
  docs/resources/aws_dms_endpoint.md
  docs/resources/aws_dms_endpoints.md
  libraries/aws_backend.rb
  libraries/aws_dms_endpoint.rb
  libraries/aws_dms_endpoints.rb
  test/integration/build/aws.tf
  test/integration/build/outputs.tf
  test/integration/verify/controls/aws_dms_endpoint.rb
  test/integration/verify/controls/aws_dms_endpoints.rb
  test/unit/resources/aws_dms_endpoint_test.rb
  test/unit/resources/aws_dms_endpoints_test.rb
Labels: Documentation, Epic

#418 Support VPC endpoint service permission(s)
  README.md
  docs/resources/aws_vpc_endpoint_service_permission.md
  docs/resources/aws_vpc_endpoint_service_permissions.md
  libraries/aws_vpc_endpoint_service_permission.rb
  libraries/aws_vpc_endpoint_service_permissions.rb
  test/integration/build/aws.tf
  test/integration/build/outputs.tf
  test/integration/verify/controls/aws_vpc_endpoint_service_permission.rb
  test/integration/verify/controls/aws_vpc_endpoint_service_permissions.rb
  test/unit/resources/aws_vpc_endpoint_service_permission_test.rb
  test/unit/resources/aws_vpc_endpoint_service_permissions_test.rb
  test/unit/resources/mock/aws_vpc_endpoint_service_permission_mock.rb
Labels: Documentation, Feature Request, Version: Bump Minor

#373 aws elasticloadbalancingv2 listener
  docs/resources/aws_elasticloadbalancingv2_listener.md
  docs/resources/aws_elasticloadbalancingv2_listeners.md
  libraries/aws_elasticloadbalancingv2_listener.rb
  libraries/aws_elasticloadbalancingv2_listeners.rb
  test/integration/build/aws.tf
  test/integration/verify/controls/aws_elasticloadbalancingv2_listener.rb
  test/integration/verify/controls/aws_elasticloadbalancingv2_listeners.rb
  test/unit/resources/aws_elasticloadbalancingv2_listener_test.rb
  test/unit/resources/aws_elasticloadbalancingv2_listeners_test.rb
Labels: Epic, Feature Request

#381 aws_glue_database
  docs/resources/aws_glue_database.md
  docs/resources/aws_glue_databases.md
  libraries/aws_backend.rb
  libraries/aws_glue_database.rb
  libraries/aws_glue_databases.rb
  test/integration/build/aws.tf
  test/integration/verify/controls/aws_glue_database.rb
  test/integration/verify/controls/aws_glue_databases.rb
  test/unit/resources/aws_glue_database_test.rb
  test/unit/resources/aws_glue_databases_test.rb
Labels: Documentation, Epic

#380 aws_glue_crawler
  docs/resources/aws_glue_crawler.md
  docs/resources/aws_glue_crawlers.md
  libraries/aws_glue_crawler.rb
  libraries/aws_glue_crawlers.rb
  libraries/aws_glue_databases.rb
  test/integration/build/aws.tf
  test/integration/configuration/aws_inspec_config.rb
  test/integration/verify/controls/aws_glue_crawler.rb
  test/integration/verify/controls/aws_glue_crawlers.rb
  test/unit/resources/aws_glue_crawler_test.rb
  test/unit/resources/aws_glue_crawlers_test.rb
Labels: Documentation, Epic

#378 aws_elastic_search_domain
  docs/resources/aws_elasticsearchservice_domain.md
  docs/resources/aws_elasticsearchservice_domains.md
  libraries/aws_backend.rb
  libraries/aws_elasticsearchservice_domain.rb
  libraries/aws_elasticsearchservice_domains.rb
  test/integration/build/aws.tf
  test/integration/build/outputs.tf
  test/integration/configuration/aws_inspec_config.rb
  test/integration/verify/controls/aws_elasticsearchservice_domain.rb
  test/integration/verify/controls/aws_elasticsearchservice_domains.rb
  test/unit/resources/aws_elastic_search_domain_test.rb
  test/unit/resources/aws_elastic_search_domains_test.rb
Labels: Documentation, Epic

#379 aws_event_rule
  docs/resources/aws_eventbridge_rule.md
  docs/resources/aws_eventbridge_rules.md
  libraries/aws_backend.rb
  libraries/aws_eventbridge_rule.rb
  libraries/aws_eventbridge_rules.rb
  test/integration/build/aws.tf
  test/integration/build/outputs.tf
  test/integration/verify/controls/aws_eventbridge_rule.rb
  test/integration/verify/controls/aws_eventbridge_rules.rb
  test/unit/resources/aws_eventbridge_rule_test.rb
  test/unit/resources/aws_eventbridge_rules_test.rb
Labels: Documentation, Epic

#423 Fix aws_auto_scaling_groups tags handling
  libraries/aws_auto_scaling_groups.rb
  test/integration/verify/controls/aws_auto_scaling_groups.rb
  test/unit/resources/aws_auto_scaling_groups_test.rb
Labels: Version: Bump Minor

#484 Ecs task definitions missing methods
  .rubocop.yml
  docs/resources/aws_ecs_task_definition.md
  docs/resources/aws_stepfunctions_state_machine.md
  docs/resources/aws_stepfunctions_state_machines.md
  libraries/aws_backend.rb
  libraries/aws_ecs_task_definition.rb
  libraries/aws_stepfunctions_state_machine.rb
  libraries/aws_stepfunctions_state_machines.rb
  test/integration/build/aws.tf
  test/integration/build/outputs.tf
  test/integration/configuration/aws_inspec_config.rb
  test/integration/verify/controls/aws_ecs_task_definition.rb
  test/integration/verify/controls/aws_stepfunctions_state_machine.rb
  test/integration/verify/controls/aws_stepfunctions_state_machines.rb
  test/unit/resources/aws_stepfunctions_state_machine_test.rb
  test/unit/resources/aws_stepfunctions_state_machines_test.rb
Labels: Documentation

#485 EBS snapshot resources
  README.md
  docs/resources/aws_ebs_snapshot.md
  docs/resources/aws_ebs_snapshots.md
  libraries/aws_ebs_snapshot.rb
  libraries/aws_ebs_snapshots.rb
  test/integration/build/aws.tf
  test/integration/build/outputs.tf
  test/integration/configuration/aws_inspec_config.rb
  test/integration/verify/controls/aws_ebs_snapshot.rb
  test/integration/verify/controls/aws_ebs_snapshots.rb
  test/integration/verify/controls/aws_ebs_snapshots_loop.rb
  test/unit/resources/aws_ebs_snapshot_test.rb
  test/unit/resources/aws_ebs_snapshots_test.rb
  test/unit/resources/mock/aws_ebs_snapshot_mock.rb
Labels: Documentation, Version: Bump Minor

#413 Subnet route table assoc resource
  docs/resources/aws_route_table.md
  docs/resources/aws_route_tables.md
  libraries/aws_route_table.rb
  libraries/aws_route_tables.rb
  test/integration/build/aws.tf
  test/integration/build/outputs.tf
  test/integration/verify/controls/aws_route_table.rb
  test/integration/verify/controls/aws_route_tables.rb
  test/unit/resources/aws_route_table_test.rb
  test/unit/resources/aws_route_tables_test.rb
Labels: Documentation, Feature Request, Version: Bump Minor

#374 aws elasticloadbalancingv2 listener_certificate
  docs/resources/aws_elasticloadbalancingv2_listener_certificate.md
  docs/resources/aws_elasticloadbalancingv2_listener_certificates.md
  libraries/aws_elasticloadbalancingv2_listener_certificate.rb
  libraries/aws_elasticloadbalancingv2_listener_certificates.rb
  test/integration/build/aws.tf
  test/integration/verify/controls/aws_elasticloadbalancingv2_listener_certificate.rb
  test/integration/verify/controls/aws_elasticloadbalancingv2_listener_certificates.rb
  test/unit/resources/aws_elasticloadbalancingv2_listener_certificate_test.rb
  test/unit/resources/aws_elasticloadbalancingv2_listener_certificates_test.rb
Labels: Do not merge, Epic

#375 aws_elasticloadbalancingv2_listener_rule
  docs/resources/aws_elasticloadbalancingv2_listener_rule.md
  docs/resources/aws_elasticloadbalancingv2_listener_rules.md
  libraries/aws_elasticloadbalancingv2_listener_rule.rb
  libraries/aws_elasticloadbalancingv2_listener_rules.rb
  test/integration/build/aws.tf
  test/integration/build/outputs.tf
  test/integration/verify/controls/aws_elasticloadbalancingv2_listener_rule.rb
  test/integration/verify/controls/aws_elasticloadbalancingv2_listener_rules.rb
  test/unit/resources/aws_elasticloadbalancingv2_listener_rule_test.rb
  test/unit/resources/aws_elasticloadbalancingv2_listener_rules_test.rb
Labels: Do not merge, Epic, Feature Request

#377 aws_elasticloadbalancingv2_target_group
  docs/resources/aws_elasticloadbalancingv2_target_group.md
  docs/resources/aws_elasticloadbalancingv2_target_groups.md
  libraries/aws_elasticloadbalancingv2_target_group.rb
  libraries/aws_elasticloadbalancingv2_target_groups.rb
  test/integration/build/aws.tf
  test/integration/build/outputs.tf
  test/integration/verify/controls/aws_elasticloadbalancingv2_target_group.rb
  test/integration/verify/controls/aws_elasticloadbalancingv2_target_groups.rb
  test/unit/resources/aws_elasticloadbalancingv2_target_group_test.rb
  test/unit/resources/aws_elasticloadbalancingv2_target_groups_test.rb
Labels: Epic

#361 Support for checking tags in aws_subnets resource
  docs/resources/aws_eks_cluster.md
  docs/resources/aws_subnets.md
  libraries/aws_subnets.rb
  test/unit/resources/aws_subnets_test.rb
Labels: Version: Bump Minor

#422 aws dms replication subnet group
  docs/resources/aws_dms_replication_subnet_group.md
  docs/resources/aws_dms_replication_subnet_groups.md
  libraries/aws_dms_replication_subnet_group.rb
  libraries/aws_dms_replication_subnet_groups.rb
  test/integration/verify/controls/aws_dms_replication_subnet_group.rb
  test/integration/verify/controls/aws_dms_replication_subnet_groups.rb
  test/unit/resources/aws_dms_replication_subnet_group_test.rb
  test/unit/resources/aws_dms_replication_subnet_groups_test.rb
Labels: Documentation, Epic

#457 aws transfer user
  docs/resources/aws_transfer_user.md
  docs/resources/aws_transfer_users.md
  libraries/aws_backend.rb
  libraries/aws_transfer_user.rb
  libraries/aws_transfer_users.rb
  test/integration/build/aws.tf
  test/integration/build/outputs.tf
  test/integration/configuration/aws_inspec_config.rb
  test/integration/verify/controls/aws_transfer_user.rb
  test/integration/verify/controls/aws_transfer_users.rb
  test/unit/resources/aws_transfer_user_test.rb
  test/unit/resources/aws_transfer_users_test.rb
Labels: Documentation, Epic, Feature Request

#458 aws stepfunctions state machine
  libraries/aws_stepfunctions_state_machine.rb
Labels: Documentation, Epic, Feature Request

#467 aws_servicecatalog_cloud_formation_product
  docs/resources/aws_servicecatalog_cloud_formation_product.md
  libraries/aws_backend.rb
  libraries/aws_servicecatalog_cloud_formation_product.rb
  test/integration/build/aws.tf
  test/integration/build/outputs.tf
  test/integration/verify/controls/aws_servicecatalog_clould_formation_product.rb
  test/unit/resources/aws_servicecatalog_clould_formation_product_test.rb
Labels: Documentation, Epic, Feature Request

#471 aws_ram_resource_share
  docs/resources/aws_ram_resource_share.md
  docs/resources/aws_ram_resource_shares.md
  libraries/aws_backend.rb
  libraries/aws_ram_resource_share.rb
  libraries/aws_ram_resource_shares.rb
  test/integration/build/aws.tf
  test/integration/build/outputs.tf
  test/integration/verify/controls/aws_ram_resource_share.rb
  test/integration/verify/controls/aws_ram_resource_shares.rb
  test/unit/resources/aws_ram_resource_share_test.rb
  test/unit/resources/aws_ram_resource_shares_test.rb
Labels: Documentation, Epic, Feature Request

#472 aws_logs_metric_filter
  docs/resources/aws_logs_metric_filter.md
  docs/resources/aws_logs_metric_filters.md
  libraries/aws_logs_metric_filter.rb
  libraries/aws_logs_metric_filters.rb
  test/integration/build/aws.tf
  test/integration/verify/controls/aws_logs_metric_filter.rb
  test/integration/verify/controls/aws_logs_metric_filters.rb
  test/unit/resources/aws_logs_metric_filter_test.rb
  test/unit/resources/aws_logs_metric_filters_test.rb
Labels: Documentation, Epic, Feature Request

#470 aws_servicecatalog_portfolio_product_association
  docs/resources/aws_servicecatalog_portfolio_product_association.md
  docs/resources/aws_servicecatalog_portfolio_product_associations.md
  libraries/aws_backend.rb
  libraries/aws_servicecatalog_portfolio_product_association.rb
  libraries/aws_servicecatalog_portfolio_product_associations.rb
  test/integration/verify/controls/aws_servicecatalog_portfolio_product_association.rb
  test/integration/verify/controls/aws_servicecatalog_portfolio_product_associations.rb
  test/unit/resources/aws_servicecatalog_portfolio_product_association_test.rb
  test/unit/resources/aws_servicecatalog_portfolio_product_associations_test.rb
Labels: Documentation, Epic, Feature Request

#474 aws_route53resolver_resolver_endpoint
  docs/resources/aws_route53resolver_resolver_endpoint.md
  docs/resources/aws_route53resolver_resolver_endpoints.md
  libraries/aws_backend.rb
  libraries/aws_route53resolver_resolver_endpoint.rb
  libraries/aws_route53resolver_resolver_endpoints.rb
  test/integration/build/aws.tf
  test/integration/build/outputs.tf
  test/integration/configuration/aws_inspec_config.rb
  test/integration/verify/controls/aws_route53_resolver_resolver_endpoint.rb
  test/integration/verify/controls/aws_route53_resolver_resolver_endpoints.rb
  test/unit/resources/aws_route53_resolver_resolver_endpoint_test.rb
  test/unit/resources/aws_route53_resolver_resolver_endpoints_test.rb
Labels: Documentation, Epic, Feature Request

#475 aws_route53resolver_resolver_rule_association
  docs/resources/aws_route53resolver_resolver_rule_association.md
  docs/resources/aws_route53resolver_resolver_rule_associations.md
  libraries/aws_route53resolver_resolver_rule_association.rb
  libraries/aws_route53resolver_resolver_rule_associations.rb
  test/integration/build/aws.tf
  test/integration/build/outputs.tf
  test/integration/verify/controls/aws_route53_resolver_resolver_rule_association.rb
  test/integration/verify/controls/aws_route53_resolver_resolver_rule_associations.rb
  test/unit/resources/aws_route53_resolver_resolver_rule_association_test.rb
  test/unit/resources/aws_route53_resolver_resolver_rule_associations_test.rb
Labels: Do not merge, Documentation, Epic, Feature Request

#468 aws_servicecatalog_launch_role_role_constraint
  docs/resources/aws_servicecatalog_launch_role_constraint.md
  docs/resources/aws_servicecatalog_launch_role_constraints.md
  libraries/aws_backend.rb
  libraries/aws_servicecatalog_launch_role_constraint.rb
  libraries/aws_servicecatalog_launch_role_constraints.rb
  test/integration/verify/controls/aws_servicecatalog_launch_role_constraint.rb
  test/integration/verify/controls/aws_servicecatalog_launch_role_constraints.rb
  test/unit/resources/aws_servicecatalog_launch_role_constraint_test.rb
  test/unit/resources/aws_servicecatalog_launch_role_constraints_test.rb
Labels: Documentation, Epic, Feature Request

#383 aws_lambda_event_source_mapping
  docs/resources/aws_lambda_event_source_mapping.md
  docs/resources/aws_lambda_event_source_mappings.md
  libraries/aws_lambda_event_source_mapping.rb
  libraries/aws_lambda_event_source_mappings.rb
  test/integration/build/aws.tf
  test/integration/build/outputs.tf
  test/integration/verify/controls/aws_lambda_event_source_mapping.rb
  test/integration/verify/controls/aws_lambda_event_source_mappings.rb
  test/unit/resources/aws_lambda_event_source_mapping_test.rb
  test/unit/resources/aws_lambda_event_source_mappings_test.rb
Labels: Documentation, Epic, Feature Request

#473 aws_route53_record_set
  docs/resources/aws_route53_record_set.md
  docs/resources/aws_route53_record_sets.md
  libraries/aws_route53_record_set.rb
  libraries/aws_route53_record_sets.rb
  test/integration/build/aws.tf
  test/integration/build/outputs.tf
  test/integration/configuration/aws_inspec_config.rb
  test/integration/verify/controls/aws_route53_record_set.rb
  test/integration/verify/controls/aws_route53_record_sets.rb
  test/unit/resources/aws_route53_record_set_test.rb
  test/unit/resources/aws_route53_record_sets_test.rb
Labels: Documentation, Epic, Feature Request

#382 aws_iam_instance_profile
  docs/resources/aws_iam_instance_profile.md
  docs/resources/aws_iam_instance_profiles.md
  libraries/aws_iam_instance_profile.rb
  libraries/aws_iam_instance_profiles.rb
  test/integration/build/aws.tf
  test/integration/build/outputs.tf
  test/integration/configuration/aws_inspec_config.rb
  test/integration/verify/controls/aws_iam_instance_profile.rb
  test/integration/verify/controls/aws_iam_instance_profiles.rb
  test/unit/resources/aws_iam_instance_profile_test.rb
  test/unit/resources/aws_iam_instance_profiles_test.rb
Labels: Documentation, Epic

#370 aws ecs service
  docs/resources/aws_ecs_service.md
  docs/resources/aws_ecs_services.md
  libraries/aws_ecs_service.rb
  libraries/aws_ecs_services.rb
  libraries/aws_ecs_task_definitions.rb
  test/integration/build/aws.tf
  test/integration/build/outputs.tf
  test/integration/configuration/aws_inspec_config.rb
  test/integration/verify/controls/aws_ecs_service.rb
  test/integration/verify/controls/aws_ecs_services.rb
  test/unit/resources/aws_ecs_service_test.rb
  test/unit/resources/aws_ecs_services_test.rb
Labels: Epic, Feature Request

#465 aws secret manager secret
  docs/resources/aws_secretsmanager_secret.md
  docs/resources/aws_secretsmanager_secrets.md
  libraries/aws_backend.rb
  libraries/aws_ec2_transit_gateway_attachment.rb
  libraries/aws_secretsmanager_secret.rb
  libraries/aws_secretsmanager_secrets.rb
  test/integration/build/aws.tf
  test/integration/build/outputs.tf
  test/integration/verify/controls/aws_secretsmanager_secret.rb
  test/integration/verify/controls/aws_secretsmanager_secrets.rb
  test/unit/resources/aws_secretsmanager_secret_test.rb
  test/unit/resources/aws_secretsmanager_secrets_test.rb
Labels: Documentation, Epic, Feature Request, Version: Bump Minor

#469 aws_servicecatalog_portfolio_principal_association
  docs/resources/aws_servicecatalog_portfolio_principal_association.md
  docs/resources/aws_servicecatalog_portfolio_principal_associations.md
  libraries/aws_servicecatalog_portfolio_principal_association.rb
  libraries/aws_servicecatalog_portfolio_principal_associations.rb
  test/integration/verify/controls/aws_servicecatalog_portfolio_principal_association.rb
  test/integration/verify/controls/aws_servicecatalog_portfolio_principal_associations.rb
  test/unit/resources/aws_servicecatalog_portfolio_principal_association_test.rb
  test/unit/resources/aws_servicecatalog_portfolio_principal_associations_test.rb
Labels: Documentation, Epic, Feature Request, Version: Bump Minor

#476 aws_route53resolver_resolver_rule
  docs/resources/aws_route53resolver_resolver_rule.md
  docs/resources/aws_route53resolver_resolver_rules.md
  libraries/aws_backend.rb
  libraries/aws_route53resolver_resolver_rule.rb
  libraries/aws_route53resolver_resolver_rules.rb
  test/integration/build/aws.tf
  test/integration/build/outputs.tf
  test/integration/configuration/aws_inspec_config.rb
  test/integration/verify/controls/aws_route53_resolver_resolver_rule.rb
  test/integration/verify/controls/aws_route53_resolver_resolver_rules.rb
  test/unit/resources/aws_route53_resolver_resolver_rule_test.rb
  test/unit/resources/aws_route53_resolver_resolver_rules_test.rb
Labels: Do not merge, Documentation, Epic, Feature Request

#478 aws_lambda_permission
  docs/resources/aws_lambda_permission.md
  docs/resources/aws_lambda_permissions.md
  libraries/aws_lambda_permission.rb
  libraries/aws_lambda_permissions.rb
  test/integration/build/aws.tf
  test/integration/verify/controls/aws_lambda_permission.rb
  test/integration/verify/controls/aws_lambda_permissions.rb
  test/unit/resources/aws_lambda_permission_test.rb
  test/unit/resources/aws_lambda_permissions_test.rb
Labels: Do not merge, Documentation, Epic, Feature Request
