Repository inspec/inspec-aws, pull requests merged in 2021-08, with the labels that each got.

#508 DynamoDB Pagination Issue Fix
  docs/resources/aws_dynamodb_tables.md
  libraries/aws_dynamodb_tables.rb
  test/integration/verify/controls/aws_dynamodb_tables.rb
Labels: Bug

#400 AWS Shield Subscription - finalize PR#272
  README.md
  docs/resources/aws_shield_subscription.md
  libraries/aws_backend.rb
  libraries/aws_shield_subscription.rb
  test/unit/resources/aws_shield_subscription_test.rb
Labels: Version: Bump Minor, Documentation

#519 Adding RDS snapshot resource
  README.md
  docs/resources/aws_rds_snapshot.md
  docs/resources/aws_rds_snapshot_attributes.md
  docs/resources/aws_rds_snapshots.md
  libraries/aws_rds_snapshot.rb
  libraries/aws_rds_snapshot_attributes.rb
  libraries/aws_rds_snapshots.rb
  test/integration/build/aws.tf
  test/integration/build/outputs.tf
  test/integration/verify/controls/aws_rds_snapshot.rb
  test/integration/verify/controls/aws_rds_snapshots.rb
  test/unit/resources/aws_rds_snapshot_attributes_test.rb
  test/unit/resources/aws_rds_snapshot_test.rb
  test/unit/resources/aws_rds_snapshots_test.rb
Labels: Version: Bump Minor, Documentation, CFT Support

#487 aws_transit_gateway_multicast_domain_association
  docs/resources/aws_transit_gateway_multicast_domain_association.md
  docs/resources/aws_transit_gateway_multicast_domain_associations.md
  libraries/aws_transit_gateway_multicast_domain_association.rb
  libraries/aws_transit_gateway_multicast_domain_associations.rb
  test/integration/verify/controls/aws_transit_gateway_multicast_domain_association.rb
  test/integration/verify/controls/aws_transit_gateway_multicast_domain_associations.rb
  test/unit/resources/aws_transit_gateway_multicast_domain_association_test.rb
  test/unit/resources/aws_transit_gateway_multicast_domain_associations_test.rb
Labels: Feature Request, Version: Bump Minor, Documentation, Epic

#486 aws_transit_gateway_multicast_domain
  docs/resources/aws_transit_gateway_multicast_domain.md
  docs/resources/aws_transit_gateway_multicast_domains.md
  libraries/aws_transit_gateway_multicast_domain.rb
  libraries/aws_transit_gateway_multicast_domains.rb
  test/integration/verify/controls/aws_transit_gateway_multicast_domain.rb
  test/integration/verify/controls/aws_transit_gateway_multicast_domains.rb
  test/unit/resources/aws_transit_gateway_multicast_domain_test.rb
  test/unit/resources/aws_transit_gateway_multicast_domains_test.rb
Labels: Feature Request, Version: Bump Minor, Documentation, Epic

#489 aws_transit_gateway_multicast_group_member
  docs/resources/aws_transit_gateway_multicast_group_member.md
  docs/resources/aws_transit_gateway_multicast_group_members.md
  libraries/aws_transit_gateway_multicast_group_member.rb
  libraries/aws_transit_gateway_multicast_group_members.rb
  test/integration/verify/controls/aws_transit_gateway_multicast_group_member.rb
  test/integration/verify/controls/aws_transit_gateway_multicast_group_members.rb
  test/unit/resources/aws_transit_gateway_multicast_group_member_test.rb
  test/unit/resources/aws_transit_gateway_multicast_group_members_test.rb
Labels: Feature Request, Version: Bump Minor, Documentation, Epic
