Repository inspec/inspec-aws, pull requests merged in 2021-09, with the labels that each got.

#516 Added feature request for origin_path in aws_cloudfront_distribution …
  docs/resources/aws_cloudfront_distribution.md
  libraries/aws_cloudfront_distribution.rb
Labels: Version: Bump Minor, Documentation, CFT Support

#488 aws_transit_gateway_connect
  docs/resources/aws_transit_gateway_connect.md
  docs/resources/aws_transit_gateway_connects.md
  libraries/aws_transit_gateway_connect.rb
  libraries/aws_transit_gateway_connects.rb
  test/integration/verify/controls/aws_transit_gateway_connect.rb
  test/integration/verify/controls/aws_transit_gateway_connects.rb
  test/unit/resources/aws_transit_gateway_connect_test.rb
  test/unit/resources/aws_transit_gateway_connects_test.rb
Labels: Feature Request, Version: Bump Minor, Documentation, Epic

#540 Replace deprecated --without flag with bundle config
  .expeditor/buildkite/verify.sh
Labels: Expeditor: Skip All

#490 aws_transit_gateway_multicast_group_source
  docs/resources/aws_transit_gateway_multicast_group_source.md
  docs/resources/aws_transit_gateway_multicast_group_sources.md
  libraries/aws_transit_gateway_multicast_group_source.rb
  libraries/aws_transit_gateway_multicast_group_sources.rb
  test/integration/verify/controls/aws_transit_gateway_multicast_group_source.rb
  test/integration/verify/controls/aws_transit_gateway_multicast_group_sources.rb
  test/unit/resources/aws_transit_gateway_multicast_group_source_test.rb
  test/unit/resources/aws_transit_gateway_multicast_group_sources_test.rb
Labels: Feature Request, Documentation, Epic

#499 soumyo/aws_ec2_vpn_gateway_route_propagation
  docs/resources/aws_ec2_vpn_gateway_route_propagation.md
  docs/resources/aws_ec2_vpn_gateway_route_propagations.md
  libraries/aws_ec2_vpn_gateway_route_propagation.rb
  libraries/aws_ec2_vpn_gateway_route_propagations.rb
  test/integration/verify/controls/aws_ec2_vpn_gateway_route_propagation.rb
  test/integration/verify/controls/aws_ec2_vpn_gateway_route_propagations.rb
  test/unit/resources/aws_ec2_vpn_gateway_route_propagation_test.rb
  test/unit/resources/aws_ec2_vpn_gateway_route_propagations_test.rb
Labels: Feature Request, Documentation, Epic

#497 soumyo/aws_ec2_vpc_peering_connection
  docs/resources/aws_ec2_vpc_peering_connection.md
  docs/resources/aws_ec2_vpc_peering_connections.md
  libraries/aws_ec2_vpc_peering_connection.rb
  libraries/aws_ec2_vpc_peering_connections.rb
  test/integration/build/aws.tf
  test/integration/build/outputs.tf
  test/integration/configuration/aws_inspec_config.rb
  test/integration/verify/controls/aws_ec2_vpc_peering_connection.rb
  test/integration/verify/controls/aws_ec2_vpc_peering_connections.rb
  test/unit/resources/aws_ec2_vpc_peering_connection_test.rb
  test/unit/resources/aws_ec2_vpc_peering_connections_test.rb
Labels: Feature Request, Documentation, Epic

#495 soumyo/aws_ec2_transit_gateway_route_table_propagation
  .byebug_history
  docs/resources/aws_ec2_transit_gateway_route_table_propagation.md
  docs/resources/aws_ec2_transit_gateway_route_table_propagations.md
  libraries/aws_ec2_transit_gateway_route_table_propagation.rb
  libraries/aws_ec2_transit_gateway_route_table_propagations.rb
  test/integration/verify/controls/aws_ec2_transit_gateway_route_table.rb
  test/integration/verify/controls/aws_ec2_transit_gateway_route_table_propagation.rb
  test/integration/verify/controls/aws_ec2_transit_gateway_route_table_propagations.rb
  test/unit/resources/aws_ec2_transit_gateway_route_table_propagation_test.rb
  test/unit/resources/aws_ec2_transit_gateway_route_table_propagations_test.rb
Labels: Feature Request, Documentation, Epic

#496 soumyo/aws_ec2_volume_attachment
  .byebug_history
  docs/resources/aws_ec2_volume_attachments.md
  libraries/aws_ec2_volume_attachments.rb
  test/integration/verify/controls/aws_ec2_volume_attachments.rb
  test/unit/resources/aws_ec2_volume_attachments_test.rb
Labels: Feature Request, Documentation, Epic

#491 Added support to audit Traffic mirror filter
  docs/resources/aws_ec2_traffic_mirror_filter.md
  docs/resources/aws_ec2_traffic_mirror_filters.md
  libraries/aws_ec2_traffic_mirror_filter.rb
  libraries/aws_ec2_traffic_mirror_filters.rb
  test/integration/build/aws.tf
  test/integration/build/outputs.tf
  test/integration/verify/controls/aws_ec2_traffic_mirror_filter.rb
  test/integration/verify/controls/aws_ec2_traffic_mirror_filters.rb
  test/unit/resources/aws_ec2_traffic_mirror_filter_test.rb
  test/unit/resources/aws_ec2_traffic_mirror_filters_test.rb
Labels: Feature Request, Documentation

#493 NIrbhay/ Traffic mirror Session
  docs/resources/aws_ec2_traffic_mirror_session.md
  docs/resources/aws_ec2_traffic_mirror_sessions.md
  libraries/aws_ec2_traffic_mirror_session.rb
  libraries/aws_ec2_traffic_mirror_sessions.rb
  test/integration/build/aws.tf
  test/integration/build/outputs.tf
  test/integration/verify/controls/aws_ec2_traffic_mirror_session.rb
  test/integration/verify/controls/aws_ec2_traffic_mirror_sessions.rb
  test/unit/resources/aws_ec2_traffic_mirror_session_test.rb
  test/unit/resources/aws_ec2_traffic_mirror_sessions_test.rb
Labels: Feature Request, Documentation, Epic

#634 Fix resource title in MD file
  docs/resources/aws_ec2_traffic_mirror_session.md
Labels: Documentation

#622 bugfix/modifying Regex for db snapshot identifier
  libraries/aws_rds_snapshot.rb
  libraries/aws_rds_snapshot_attributes.rb
Labels: Version: Bump Minor, CFT Support

#633 adding attributes for cloud front distribution
  .rubocop.yml
  docs/resources/aws_cloudfront_distribution.md
  libraries/aws_cloudfront_distribution.rb
Labels: Version: Bump Minor, CFT Support

#520 soumyo/plural_resource_s3_bucket_objects
  docs/resources/aws_s3_bucket_object.md
  docs/resources/aws_s3_bucket_objects.md
  libraries/aws_s3_bucket_objects.rb
  test/integration/verify/controls/aws_s3_bucket_objects.rb
  test/unit/resources/aws_s3_bucket_objects_test.rb
Labels: Feature Request, Documentation, Epic

#498 soumyo/aws_ec2_vpn_connection_route
  docs/resources/aws_ec2_vpn_connection_routes.md
  libraries/aws_ec2_vpn_connection_routes.rb
  test/integration/build/aws.tf
  test/integration/build/outputs.tf
  test/integration/configuration/aws_inspec_config.rb
  test/integration/verify/controls/aws_ec2_vpn_connection_routes.rb
  test/unit/resources/aws_ec2_vpn_connection_routes_test.rb
Labels: Feature Request, Documentation, Epic

#524 soumyo/aws_ec2_network_insights_analysis
  docs/resources/aws_ec2_network_insights_analysis.md
  docs/resources/aws_ec2_network_insights_analysis_plural.md
  libraries/aws_ec2_network_insights_analysis.rb
  libraries/aws_ec2_network_insights_analysis_plural.rb
  test/integration/verify/controls/aws_ec2_network_insights_analysis.rb
  test/integration/verify/controls/aws_ec2_network_insights_analysis_plural.rb
  test/unit/resources/aws_ec2_network_insights_analysis_plural_test.rb
  test/unit/resources/aws_ec2_network_insights_analysis_test.rb
Labels: Feature Request, Documentation, Epic, 2021_PQ4

#523 soumyo/aws_ec2_internet_gateway
  docs/resources/aws_ec2_internet_gateway.md
  docs/resources/aws_ec2_internet_gateways.md
  libraries/aws_ec2_internet_gateway.rb
  libraries/aws_ec2_internet_gateways.rb
  test/integration/build/aws.tf
  test/integration/build/outputs.tf
  test/integration/verify/controls/aws_ec2_internet_gateway.rb
  test/integration/verify/controls/aws_ec2_internet_gateways.rb
  test/unit/resources/aws_ec2_internet_gateway_test.rb
  test/unit/resources/aws_ec2_internet_gateways_test.rb
Labels: Feature Request, Documentation, Epic, 2021_PQ4

#525 soumyo/aws_ec2_network_insights_path
  docs/resources/aws_ec2_network_insights_path.md
  docs/resources/aws_ec2_network_insights_paths.md
  libraries/aws_ec2_network_insights_path.rb
  libraries/aws_ec2_network_insights_paths.rb
  test/integration/verify/controls/aws_ec2_network_insights_path.rb
  test/integration/verify/controls/aws_ec2_network_insights_paths.rb
  test/unit/resources/aws_ec2_network_insights_path_test.rb
  test/unit/resources/aws_ec2_network_insights_paths_test.rb
Labels: Feature Request, Documentation, Epic, 2021_PQ4

#526 soumyo/aws_ec2_network_interface
  docs/resources/aws_ec2_network_interface.md
  docs/resources/aws_ec2_network_interfaces.md
  libraries/aws_ec2_network_interface.rb
  libraries/aws_ec2_network_interfaces.rb
  test/integration/build/aws.tf
  test/integration/build/outputs.tf
  test/integration/verify/controls/aws_ec2_network_interface.rb
  test/integration/verify/controls/aws_ec2_network_interfaces.rb
  test/unit/resources/aws_ec2_network_interface_test.rb
  test/unit/resources/aws_ec2_network_interfaces_test.rb
Labels: Feature Request, Documentation, Epic, 2021_PQ4

#632 Scripts to automate release notes & announcement
  .expeditor/announce-release.sh
  .expeditor/publish-release-notes.sh
Labels: Documentation

#527 soumyo/aws_ec2_network_interface_attachment
  docs/resources/aws_ec2_network_interface_attachment.md
  docs/resources/aws_ec2_network_interface_attachments.md
  libraries/aws_ec2_network_interface_attachment.rb
  libraries/aws_ec2_network_interface_attachments.rb
  test/integration/verify/controls/aws_ec2_network_interface_attachment.rb
  test/integration/verify/controls/aws_ec2_network_interface_attachments.rb
  test/unit/resources/aws_ec2_network_interface_attachment_test.rb
  test/unit/resources/aws_ec2_network_interface_attachments_test.rb
Labels: Feature Request, Documentation, Epic, 2021_PQ4

#621 Inline policy names for IAM Groups
  docs/resources/aws_iam_group.md
  docs/resources/aws_iam_groups.md
  libraries/aws_iam_group.rb
  libraries/aws_iam_groups.rb
Labels: Version: Bump Minor, Documentation, CFT Support

#650 Add releases as a Hugo module
  .expeditor/publish-release-notes.sh
  docs-chef-io/go.mod
  docs-chef-io/static/release-notes/inspec-aws/release-dates.json
Labels: Documentation

#653 Change date format in publish-release-notes script
  .expeditor/publish-release-notes.sh
Labels: Documentation

#623 Adding attributes for ELB resource
  docs/resources/aws_elb.md
  libraries/aws_elb.rb
Labels: Version: Bump Minor, Documentation, CFT Support

#522 adding tags attribute to KMS key resource
  docs/resources/aws_kms_key.md
  libraries/aws_kms_key.rb
Labels: Version: Bump Minor, Documentation, CFT Support
