Repository inspec/inspec-aws, pull requests merged in 2021-06, with the labels that each got.

#417 Minor docs fixes
  docs/resources/aws_cloudwatch_log_group.md
  docs/resources/aws_dhcp_options.md
  docs/resources/aws_ec2_dhcp_options.md
  docs/resources/aws_ec2_launch_templates.md
Labels: Documentation

#362 aws athena work group
  docs/resources/aws_athena_work_group.md
  docs/resources/aws_athena_work_groups.md
  libraries/aws_athena_work_group.rb
  libraries/aws_athena_work_groups.rb
  libraries/aws_backend.rb
  test/integration/build/aws.tf
  test/integration/build/outputs.tf
  test/integration/configuration/aws_inspec_config.rb
  test/integration/verify/controls/aws_athena_work_group.rb
  test/integration/verify/controls/aws_athena_work_groups.rb
  test/unit/resources/aws_athena_work_group_test.rb
  test/unit/resources/aws_athena_work_groups_test.rb
Labels: Documentation, Epic

#363 aws autoscaling scaling policy
  docs/resources/aws_autoscaling_scaling_policies.md
  docs/resources/aws_autoscaling_scaling_policy.md
  libraries/aws_autoscaling_scaling_policies.rb
  libraries/aws_autoscaling_scaling_policy.rb
  libraries/aws_backend.rb
  test/integration/build/aws.tf
  test/integration/build/outputs.tf
  test/integration/configuration/aws_inspec_config.rb
  test/integration/verify/controls/aws_autoscaling_scaling_policies.rb
  test/integration/verify/controls/aws_autoscaling_scaling_policy.rb
  test/unit/resources/aws_autoscaling_scaling_policies_test.rb
  test/unit/resources/aws_autoscaling_scaling_policy_test.rb
Labels: Documentation, Epic

#367 Soumyo/aws cognito identity pool
  docs/resources/aws_cognito_identity_pool.md
  docs/resources/aws_cognito_identity_pools.md
  libraries/aws_backend.rb
  libraries/aws_cognito_identity_pool.rb
  libraries/aws_cognito_identity_pools.rb
  test/integration/build/aws.tf
  test/integration/build/inspec-logo.png
  test/integration/build/outputs.tf
  test/integration/configuration/aws_inspec_config.rb
  test/integration/verify/controls/aws_cognito_identity_pool.rb
  test/integration/verify/controls/aws_cognito_identity_pools.rb
  test/unit/resources/aws_cognito_identity_pool_test.rb
  test/unit/resources/aws_cognito_identity_pools_test.rb
Labels: Documentation, Epic

#369 aws cognito userpool
  docs/resources/aws_cognito_userpool.md
  docs/resources/aws_cognito_userpools.md
  libraries/aws_backend.rb
  libraries/aws_cognito_userpool.rb
  libraries/aws_cognito_userpools.rb
  test/integration/build/aws.tf
  test/integration/build/outputs.tf
  test/integration/configuration/aws_inspec_config.rb
  test/integration/verify/controls/aws_cognito_userpool.rb
  test/integration/verify/controls/aws_cognito_userpools.rb
  test/unit/resources/aws_cognito_userpool_test.rb
  test/unit/resources/aws_cognito_userpools_test.rb
Labels: Documentation, Epic

#368 aws cognito userpool client
  docs/resources/aws_cognito_userpool_client.md
  docs/resources/aws_cognito_userpool_clients.md
  libraries/aws_cognito_userpool_client.rb
  libraries/aws_cognito_userpool_clients.rb
  test/integration/build/aws.tf
  test/integration/build/outputs.tf
  test/integration/configuration/aws_inspec_config.rb
  test/integration/verify/controls/aws_cognito_userpoolclient.rb
  test/integration/verify/controls/aws_cognito_userpoolclients.rb
  test/unit/resources/aws_cognito_userpool_client_test.rb
  test/unit/resources/aws_cognito_userpool_clients_test.rb
Labels: Documentation, Epic

#384 VPC endpoint services resource(s)
  README.md
  docs/resources/aws_vpc_endpoint_service.md
  docs/resources/aws_vpc_endpoint_services.md
  libraries/aws_vpc_endpoint_service.rb
  libraries/aws_vpc_endpoint_services.rb
  test/integration/build/outputs.tf
  test/integration/verify/controls/aws_vpc_endpoint_service.rb
  test/integration/verify/controls/aws_vpc_endpoint_services.rb
  test/unit/resources/aws_vpc_endpoint_service_test.rb
  test/unit/resources/aws_vpc_endpoint_services_test.rb
  test/unit/resources/mock/aws_vpc_endpoint_service_mock.rb
Labels: Documentation, Feature Request, Version: Bump Minor

#366 aws batch job queues
  docs/resources/aws_batch_job_queue.md
  docs/resources/aws_batch_job_queues.md
  libraries/aws_backend.rb
  libraries/aws_batch_job_queue.rb
  libraries/aws_batch_job_queues.rb
  test/integration/build/aws.tf
  test/integration/build/outputs.tf
  test/integration/configuration/aws_inspec_config.rb
  test/integration/verify/controls/aws_batch_job_queue.rb
  test/integration/verify/controls/aws_batch_job_queues.rb
  test/unit/resources/aws_batch_job_queue.rb
  test/unit/resources/aws_batch_job_queues.rb
Labels: Documentation, Epic

#364 aws batch compute environments
  docs/resources/aws_batch_compute_environment.md
  docs/resources/aws_batch_compute_environments.md
  libraries/aws_backend.rb
  libraries/aws_batch_compute_environment.rb
  libraries/aws_batch_compute_environments.rb
  test/integration/build/aws.tf
  test/integration/verify/controls/aws_batch_compute_environment.rb
  test/integration/verify/controls/aws_batch_compute_environments.rb
  test/unit/resources/aws_batch_compute_environment_test.rb
  test/unit/resources/aws_batch_compute_environments_test.rb
Labels: Do not merge, Documentation, Epic

#365 aws batch job definition
  docs/resources/aws_batch_job_definition.md
  docs/resources/aws_batch_job_definitions.md
  libraries/aws_batch_job_definition.rb
  libraries/aws_batch_job_definitions.rb
  test/integration/build/aws.tf
  test/integration/build/outputs.tf
  test/integration/configuration/aws_inspec_config.rb
  test/integration/verify/controls/aws_batch_job_definition.rb
  test/integration/verify/controls/aws_batch_job_definitions.rb
  test/unit/resources/aws_batch_job_definition_test.rb
  test/unit/resources/aws_batch_job_definitions_test.rb
Labels: Documentation, Epic

#371 ecs task definitions
  docs/resources/aws_ecs_task_definition.md
  docs/resources/aws_ecs_task_definitions.md
  docs/resources/aws_vpc.md
  docs/resources/aws_vpc_endpoint_notification.md
  docs/resources/aws_vpc_endpoint_notifications.md
  docs/resources/aws_vpcs.md
  libraries/aws_ecs_task_definition.rb
  libraries/aws_ecs_task_definitions.rb
  test/integration/build/aws.tf
  test/integration/build/outputs.tf
  test/integration/verify/controls/aws_ecs_task_definition.rb
  test/integration/verify/controls/aws_ecs_task_definitions.rb
  test/unit/resources/aws_ecs_task_definition_test.rb
  test/unit/resources/aws_ecs_task_definitions_test.rb
Labels: Documentation, Epic

#372 efs mount target
  docs/resources/aws_efs_mount_target.md
  docs/resources/aws_efs_mount_targets.md
  libraries/aws_efs_mount_target.rb
  libraries/aws_efs_mount_targets.rb
  test/integration/build/aws.tf
  test/integration/build/outputs.tf
  test/integration/verify/controls/aws_efs_mount_target.rb
  test/integration/verify/controls/aws_efs_mount_targets.rb
  test/unit/resources/aws_efs_mount_target_test.rb
  test/unit/resources/aws_efs_mount_targets_test.rb
Labels: Documentation, Epic

#460 Minor docs fixes
  docs/resources/aws_config_recorder.md
  docs/resources/aws_rds_group_options.md
  docs/resources/aws_rds_instances.md
Labels: Documentation

#427 aws_api_gateway_method
  docs/resources/aws_api_gateway_method.md
  docs/resources/aws_api_gateway_methods.md
  libraries/aws_api_gateway_method.rb
  libraries/aws_api_gateway_methods.rb
  libraries/aws_backend.rb
  test/integration/verify/controls/aws_api_gateway_method.rb
  test/integration/verify/controls/aws_api_gateway_methods.rb
  test/unit/resources/aws_api_gateway_method_test.rb
  test/unit/resources/aws_api_gateway_methods_test.rb
Labels: Documentation, Epic, Feature Request

#429 aws_application_autoscaling_scalable_target
  docs/resources/aws_application_autoscaling_scalable_target.md
  docs/resources/aws_application_autoscaling_scalable_targets.md
  libraries/aws_application_autoscaling_scalable_target.rb
  libraries/aws_application_autoscaling_scalable_targets.rb
  libraries/aws_backend.rb
  test/integration/build/aws.tf
  test/integration/verify/controls/aws_application_autoscaling_scalable_target.rb
  test/integration/verify/controls/aws_application_autoscaling_scalable_targets.rb
  test/unit/resources/aws_application_autoscaling_scalable_target_test.rb
  test/unit/resources/aws_application_autoscaling_scalable_targets_test.rb
Labels: Documentation, Epic, Feature Request

#430 aws_application_autoscaling_scaling_policy
  docs/resources/aws_application_autoscaling_scaling_policies.md
  docs/resources/aws_application_autoscaling_scaling_policy.md
  libraries/aws_application_autoscaling_scaling_policies.rb
  libraries/aws_application_autoscaling_scaling_policy.rb
  test/integration/verify/controls/aws_application_autoscaling_scaling_policies.rb
  test/integration/verify/controls/aws_application_autoscaling_scaling_policy.rb
  test/unit/resources/aws_application_autoscaling_scaling_policies_test.rb
  test/unit/resources/aws_application_autoscaling_scaling_policy_test.rb
Labels: Documentation, Epic, Feature Request

#420 aws dms replication instance
  docs/resources/aws_dms_replication_instance.md
  docs/resources/aws_dms_replication_instances.md
  libraries/aws_backend.rb
  libraries/aws_dms_replication_instance.rb
  libraries/aws_dms_replication_instances.rb
  test/integration/build/aws.tf
  test/integration/verify/controls/aws_dms_replication_instance.rb
  test/integration/verify/controls/aws_dms_replication_instances.rb
  test/unit/resources/aws_dms_replication_instance_test.rb
  test/unit/resources/aws_dms_replication_instances_test.rb
Labels: Documentation, Epic

#477 updating expeditor configurations
  .expeditor/.config.yml.swp
  .expeditor/config.yml
Labels: Expeditor: Skip All
