Repository inspec/inspec-aws, pull requests merged in 2022-02, with the labels that each got.

#824 Cache implementation for for SAP use case.
  docs/resources/aws_security_group.md
  docs/resources/aws_security_groups.md
  libraries/aws_backend.rb
  libraries/aws_security_group.rb
  libraries/aws_security_groups.rb
  test/integration/verify/controls/aws_security_groups.rb
  test/unit/resources/aws_security_groups_test.rb
Labels: Documentation, CFT Support, ReadyForDocs

#834 Lazy load tags
  libraries/aws_s3_buckets.rb
Labels: Version: Bump Minor, CFT Support

#833 Support in memory cache aws eks clusters
  docs/resources/aws_eks_cluster.md
  libraries/aws_eks_cluster.rb
  libraries/aws_eks_clusters.rb
  test/unit/resources/aws_eks_clusters_test.rb
Labels: Version: Bump Minor, Documentation, CFT Support, ReadyForDocs

#828 Support cache aws rds instance
  docs/resources/aws_rds_instance.md
  docs/resources/aws_rds_instances.md
  libraries/aws_rds_instance.rb
  libraries/aws_rds_instances.rb
  test/unit/resources/aws_rds_instances_test.rb
Labels: Version: Bump Minor, Documentation, CFT Support, ReadyForDocs

#845 soumyo/aws_ssm_resource_data_syncs
  docs/resources/aws_ssm_resource_data_syncs.md
  libraries/aws_ssm_resource_data_syncs.rb
  test/integration/verify/controls/aws_ssm_resource_data_syncs.rb
  test/unit/resources/aws_ssm_resource_data_syncs_test.rb
Labels: Feature Request, Documentation, 2021_PQ4, ReadyForDocs

#844 soumyo/aws_ssm_patch_baseline
  docs/resources/aws_ssm_patch_baseline.md
  docs/resources/aws_ssm_patch_baselines.md
  libraries/aws_ssm_patch_baseline.rb
  libraries/aws_ssm_patch_baselines.rb
  test/integration/verify/controls/aws_ssm_patch_baseline.rb
  test/integration/verify/controls/aws_ssm_patch_baselines.rb
  test/unit/resources/aws_ssm_patch_baseline_test.rb
  test/unit/resources/aws_ssm_patch_baselines_test.rb
Labels: Feature Request, Documentation, Epic, 2021_PQ4, ReadyForDocs

#850 AWSApiGatewayDocumentationVersion
  docs/resources/aws_api_gateway_documentation_version.md
  docs/resources/aws_api_gateway_documentation_versions.md
  libraries/aws_api_gateway_documentation_version.rb
  libraries/aws_api_gateway_documentation_versions.rb
  test/integration/verify/controls/aws_api_gateway_documentation_version.rb
  test/integration/verify/controls/aws_api_gateway_documentation_versions.rb
  test/unit/resources/aws_api_gateway_documentation_version_test.rb
  test/unit/resources/aws_api_gateway_documentation_versions_test.rb
Labels: Feature Request, Documentation, Epic, ReadyForDocs

#847 soumyo/update_readme_file_upto_feb9
  README.md
Labels: Do not merge, 2021_PQ4

#856 adding missing error handling for aws iam password policy resource
  libraries/aws_iam_password_policy.rb
Labels: Version: Bump Minor

#868 Fix resource page title
  docs-chef-io/content/inspec/resources/aws_ssm_patch_baselines.md
Labels: Documentation

#858 RESOURCE-170 soumyo/aws_ssm_maintenance_window_task
  docs-chef-io/content/inspec/resources/aws_ssm_maintenance_window_task.md
  docs-chef-io/content/inspec/resources/aws_ssm_maintenance_window_tasks.md
  libraries/aws_ssm_maintenance_window_task.rb
  libraries/aws_ssm_maintenance_window_tasks.rb
  test/integration/verify/controls/aws_ssm_maintenance_window_task.rb
  test/integration/verify/controls/aws_ssm_maintenance_window_tasks.rb
  test/unit/resources/aws_ssm_maintenance_window_task_test.rb
  test/unit/resources/aws_ssm_maintenance_window_tasks_test.rb
Labels: Feature Request, Documentation, ReadyForDocs, 2022_PQ1

#865 RESOURCE-169 soumyo/aws_synthetics_canary
  docs-chef-io/content/inspec/resources/aws_synthetics_canaries.md
  docs-chef-io/content/inspec/resources/aws_synthetics_canary.md
  libraries/aws_backend.rb
  libraries/aws_synthetics_canaries.rb
  libraries/aws_synthetics_canary.rb
  test/integration/build/aws.tf
  test/integration/build/outputs.tf
  test/integration/verify/controls/aws_synthetics_canaries.rb
  test/integration/verify/controls/aws_synthetics_canary.rb
  test/unit/resources/aws_synthetics_canaries_test.rb
  test/unit/resources/aws_synthetics_canary_test.rb
Labels: Feature Request, Documentation, ReadyForDocs, 2022_PQ1

#866 RESOURCE-172 soumyo/aws_stepfunctions_activity
  docs-chef-io/content/inspec/resources/aws_stepfunctions_activities.md
  docs-chef-io/content/inspec/resources/aws_stepfunctions_activity.md
  docs-chef-io/resources/aws_stepfunctions_activities.md
  docs-chef-io/resources/aws_stepfunctions_activity.md
  libraries/aws_stepfunctions_activities.rb
  libraries/aws_stepfunctions_activity.rb
  test/integration/build/aws.tf
  test/integration/build/outputs.tf
  test/integration/verify/controls/aws_stepfunctions_activities.rb
  test/integration/verify/controls/aws_stepfunctions_activity.rb
  test/unit/resources/aws_stepfunctions_activities_test.rb
  test/unit/resources/aws_stepfunctions_activity_test.rb
Labels: Feature Request, Documentation, ReadyForDocs, 2022_PQ1

#864 nirbhay/aws_api_gateway_model
  docs-chef-io/content/inspec/resources/aws_api_gateway_model.md
  docs-chef-io/content/inspec/resources/aws_api_gateway_models.md
  docs-chef-io/resources/aws_api_gateway_model.md
  docs-chef-io/resources/aws_api_gateway_models.md
  libraries/aws_api_gateway_model.rb
  libraries/aws_api_gateway_models.rb
  test/integration/build/aws.tf
  test/integration/build/outputs.tf
  test/integration/verify/controls/aws_api_gateway_model.rb
  test/integration/verify/controls/aws_api_gateway_models.rb
  test/unit/resources/aws_api_gateway_model_test.rb
  test/unit/resources/aws_api_gateway_models_test.rb
Labels: Feature Request, Documentation, ReadyForDocs, 2022_PQ1

#867 nirbhay/aws_api_gateway_response
  docs-chef-io/content/inspec/resources/aws_api_gateway_response.md
  docs-chef-io/content/inspec/resources/aws_api_gateway_responses.md
  libraries/aws_api_gateway_response.rb
  libraries/aws_api_gateway_responses.rb
  test/integration/build/outputs.tf
  test/integration/verify/controls/aws_api_gateway_response.rb
  test/integration/verify/controls/aws_api_gateway_responses.rb
  test/unit/resources/aws_api_gateway_response_test.rb
  test/unit/resources/aws_api_gateway_responses_test.rb
Labels: Feature Request, Documentation, ReadyForDocs, 2022_PQ1

#873 Remove redundant docs
  docs-chef-io/resources/aws_api_gateway_model.md
  docs-chef-io/resources/aws_api_gateway_models.md
  docs-chef-io/resources/aws_stepfunctions_activities.md
  docs-chef-io/resources/aws_stepfunctions_activity.md
Labels: Documentation

#875 Fix identifier in MD page
  docs-chef-io/content/inspec/resources/aws_ssm_patch_baselines.md
Labels: Documentation
