Repository inspec/inspec-aws, pull requests merged in 2022-01, with the labels that each got.

#811 soumyo/aws_hosted_zone_all_record_issue_fix
  docs/resources/aws_hosted_zones.md
  libraries/aws_hosted_zones.rb
  test/integration/build/outputs.tf
  test/integration/verify/controls/aws_hosted_zones.rb
  test/unit/resources/aws_hosted_zones_test.rb
Labels: Bug, Documentation, 2021_PQ4, ReadyForDocs

#808 nirbhay/aws_waf_web_acl
  docs/resources/aws_waf_web_acl.md
  docs/resources/aws_waf_web_acls.md
  libraries/aws_waf_web_acl.rb
  libraries/aws_waf_web_acls.rb
  test/integration/build/aws.tf
  test/integration/build/outputs.tf
  test/integration/verify/controls/aws_waf_web_acl.rb
  test/integration/verify/controls/aws_waf_web_acls.rb
  test/unit/resources/aws_waf_web_acl_test.rb
  test/unit/resources/aws_waf_web_acls_test.rb
Labels: Feature Request, Documentation, Epic, 2021_PQ4, ReadyForDocs

#812 soumyo/update_readme_till_sprint_15
  README.md
Labels: Feature Request, Documentation, 2021_PQ4

#817 Move release dates JSON file to assets dir
  .expeditor/publish-release-notes.sh
  docs-chef-io/assets/release-notes/inspec-aws/release-dates.json
Labels: Documentation

#818 Promote release notes 2022-01-07
  docs-chef-io/assets/release-notes/inspec-aws/release-dates.json
  docs-chef-io/static/release-notes/inspec-aws/2022-01-07.md
  docs-chef-io/static/release-notes/inspec-aws/release-dates.json
Labels: Documentation

#820 Fix/ECR infinite loop when 1000+ container registries in account
  libraries/aws_ecr_repositories.rb
Labels: Version: Bump Minor

#829 Fix title in resource doc
  docs/resources/aws_waf_size_constraint_sets.md
Labels: Documentation

#810 Added Pagination for the Route53
  docs/resources/aws_route53_record_sets.md
  libraries/aws_route53_record_sets.rb
Labels: Documentation, ReadyForDocs

#831 Remove release notes content from static dir
  .expeditor/publish-release-notes.sh
  docs-chef-io/static/release-notes/inspec-aws/2021-10-01.md
  docs-chef-io/static/release-notes/inspec-aws/2021-10-13.md
  docs-chef-io/static/release-notes/inspec-aws/2021-11-08.md
  docs-chef-io/static/release-notes/inspec-aws/2021-11-30.md
  docs-chef-io/static/release-notes/inspec-aws/2022-01-07.md
  docs-chef-io/static/release-notes/inspec-aws/release-dates.json
Labels: Documentation
