Repository inspec/inspec-aws, pull requests merged in 2022-03, with the labels that each got.

#878 Resource 234 aws api gateway request validator
  docs-chef-io/content/inspec/resources/aws_api_gateway_request_validator.md
  docs-chef-io/content/inspec/resources/aws_api_gateway_request_validators.md
  libraries/aws_api_gateway_request_validator.rb
  libraries/aws_api_gateway_request_validators.rb
  test/integration/build/aws.tf
  test/integration/build/outputs.tf
  test/integration/verify/controls/aws_api_gateway_request_validator.rb
  test/integration/verify/controls/aws_api_gateway_request_validators.rb
  test/unit/resources/aws_api_gateway_request_validator_test.rb
  test/unit/resources/aws_api_gateway_request_validators_test.rb
Labels: Feature Request, Documentation, ReadyForDocs

#884 Resource 220 lazy load aws iam users
  inspec.yml
  libraries/aws_iam_users.rb
Labels: Version: Bump Minor

#887 Resource 221 lazy load iam user
  libraries/aws_iam_user.rb
Labels: Feature Request

#889 Fix a few things in Netlify
  docs-chef-io/Makefile
  docs-chef-io/netlify.toml
Labels: Documentation

#891 Resource 223 aws alb optimization
  libraries/aws_alb.rb
  test/unit/resources/aws_alb_test.rb
Labels: Version: Bump Minor
