Repository inspec/inspec-aws, pull requests merged in 2023-01, with the labels that each got.

#957 Update AWS SNS topic subscription properties documentation
  docs-chef-io/content/inspec/resources/aws_sns_subscription.md
Labels: Documentation, ReadyForDocs

#882 RESOURCE-557 Soumyo/adding the missing attributes in sqs queue
  docs-chef-io/content/inspec/resources/aws_sqs_queue.md
  libraries/aws_sqs_queue.rb
  test/integration/verify/controls/aws_sqs_queue.rb
  test/unit/resources/aws_api_gateway_v2_apis_test.rb
Labels: Documentation, ReadyForDocs, tech-debt

#963 testing bump with git PR tag
  README.md
Labels: Version: Bump Minor
